### ISSUE TITLE
Exception caught

### ISSUE THREAD

**Issue by shaman-narayanasamy** [ablab/quast#10]
Hi,

I am obtaining this error when trying to run `QUAST`

```
list index out of range
Traceback (most recent call last):
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/quast-master/metaquast.py", line 707, in <module>
    return_code = main(sys.argv[1:])
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/quast-master/metaquast.py", line 559, in main
    ref_fpaths = search_references_meta.do(assemblies, downloaded_dirpath)
  File "/mnt/gaiagpfs/projects/ecosystem_biology/local_tools/quast-master/libs/search_references_meta.py", line 283, in do
    idy = float(line[2])
IndexError: list index out of range
```

Is there something wrong with my data?

**Comment by alexeigurevich** [comment]
Hi! We need more details for debugging: 
metaquast.log and blast log (somewhere here:  <quast_output_dir>/quast_downloaded_references/blast.res_<assembly_name>)

Are you using Quast v.3.1 or version in "master" branch of the repo?
In "master" we now skip lines which has less than 11 entries, so line[2] will always correct. In v.3.1 we didn't have this. But it is interesting to detect, why this "incorrect" lines appear

**Comment by shaman-narayanasamy** [comment]
Hi,

Thanks for the reply. I can't to attach the log files here for some reason...

What I can tell you is that the `blast.err` file is empty. And the metaquast.log contains the same error at the end.

Can I send the file via e-mail?

-Shaman-

**Comment by alexeigurevich** [comment]
Hi,
Yes, sure, please send it to quast.support@bioinf.spbau.ru

I am interested in blast alignment log (not "err"), it should be saved in QUAST_OUTPUT_DIRECTORY/quast_downloaded_references/blast.res_ASSEMBLY_NAME

**Comment by shaman-narayanasamy** [comment]
I sent you a tar.gz file with all the relevant information you might need. 

Let me know if fail to received the files via WeTransfer or if you require anything else.

**Comment by shaman-narayanasamy** [comment]
Hi,
Any updates regarding this issue? I pulled the latest master branch, but this error still pops up... Are you able to reproduce it?

**Comment by alexeigurevich** [comment]
Hi Shaman!
Sorry for the delay, it seems that we finally found and fixed this tricky bug! Could you try the latest version of source code in master branch?

**Comment by shaman-narayanasamy** [comment]
Hi Alexei!

Thanks for the quick reply. I pulled the latest changes and started the run. I will report the progress to you.

**Comment by shaman-narayanasamy** [comment]
Hi Alexei!

I tried to rerun the analysis. It ran longer than previously, but I am now faced with this error:

```
[Errno 17] File exists: '/scratch/users/snarayanasamy/IMP_MS_data/quast_X310763260-20151021/combined_reference/../quast_corrected_input/split_ref'
Traceback (most recent call last):
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/quast/metaquast.py", line 746, in <module>
    return_code = main(sys.argv[1:])
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/quast/metaquast.py", line 644, in main
    num_notifications_tuple=total_num_notifications, is_first_run=True)
  File "/mnt/nfs/projects/ecosystem_biology/local_tools/quast/metaquast.py", line 159, in _start_quast_main
    return_code = quast.main(args)
  File "/mnt/gaiagpfs/projects/ecosystem_biology/local_tools/quast/quast.py", line 633, in main
    ref_fpath = _correct_reference(ref_fpath, corrected_dirpath)
  File "/mnt/gaiagpfs/projects/ecosystem_biology/local_tools/quast/quast.py", line 278, in _correct_reference
    if not correct_fasta(ref_fpath, corr_fpath, qconfig.min_contig, is_reference=True):
  File "/mnt/gaiagpfs/projects/ecosystem_biology/local_tools/quast/quast.py", line 113, in correct_fasta
    os.makedirs(split_ref_dirpath)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/scratch/users/snarayanasamy/IMP_MS_data/quast_X310763260-20151021/combined_reference/../quast_corrected_input/split_ref'
```

My command seems to be fine. Would you like me to send the log file?

Best regards,
Shaman

**Comment by shaman-narayanasamy** [comment]
Update:

I ran the analysis again. But, this time, instead of using it without references, I used the previously downloaded references from the failed run with the `-R` flag and it worked with no issues.

Let me know if you need more information to better allow you to fix the bug.
