### ISSUE TITLE
[Errno 26] Text file busy

### ISSUE THREAD

**Issue by HappyCondaUser** [ablab/quast#100]
run into problems with "Text file busy: 'quast-out/quast_corrected_input'".  In the quast-out directory quast_corrected_input is actually a directory and not a file and it is empty.

**Comment by alexeigurevich** [comment]
Sorry for the late reply. This error is probably not directly related to Quast, it is mostly a Unix message that means that some other process or user is accessing your file (note: in Unix, the word "file" may usually mean a directory, too).
See also: https://stackoverflow.com/questions/16764946/what-generates-the-text-file-busy-message-in-unix

Is it possible that you or someone else was running another Quast process with exactly the same output directory (`quast-out` in your case)? Please try to avoid this in future.

I will close the issue now, please reopen if my advice doesn't work and the problem persists!
