### ISSUE TITLE
metaQUAST gene calling

### ISSUE THREAD

**Issue by shaman-narayanasamy** [ablab/quast#11]
Hi,

I would like to know if metaQUAST calls only complete genes or includes partial genes in the counts of unique genes?

Looking forward to your reply.

Best,
Shaman

**Comment by almiheenko** [comment]
Hi! 

MetaQUAST uses MetaGeneMark for gene prediction, which was developed especially for short metagenomic sequences and can predict partial genes with length greater than 60 nucleotides. Its algorithm for gene identification was described in the article "Ab initio gene identification in metagenomic sequences" (http://nar.oxfordjournals.org/content/38/12/e132.full).

**Comment by shaman-narayanasamy** [comment]
Hi! Noted, thanks for the information :)
