### ISSUE TITLE
ERROR! Skipping, non-ACGTN characters

### ISSUE THREAD

**Issue by Caro-Ca** [ablab/quast#110]
Hi!
I am trying to align two assemblers and visualize them with Icarus. This is the code I ran: 
`python icarus.py --threads 4 --bam ~/Quast/WNanoF.bam ~/Quast/CRRNanoF.bam `

and I've got an error: 
`ERROR! Skipping ~/Quast/CRRNanoF.bam because it contains non-ACGTN characters.`

Could you advice me what it's missing? 

Thank you in advance!

**Comment by alexeigurevich** [comment]
Hi!
You didn't specify any option before `~/Quast/CRRNanoF.bam` (like `--bam`), so it was interpreted by our tool as an assembly (the default behavior). In any assembly file, we expect to see only A,C,G,T, or N characters and a `bam` file obviously contains non-ACGTN characters, so the utility crashed with the corresponding error message.

However, there are other issues with your command as well, if I understand it correctly. First, your bams are probably alignments of assemblies against a reference genome, while we accept only bams representing *reads alignments* against the assemblies (or reference). Please check the manual regarding this. Second, you can't specify only bam files to our tools (Quast, Icarus, etc) -- we require at least one assembly file (in FASTA format) for the analysis.

The usual use case for our tools is to provide several assemblies and a reference file (if available) in FASTA format. We will align assemblies against the reference using embedded software (minimap2 aligner in the latest Quast releases) and provide you with all quality stats and visualizations, including Icarus ones. 
So, if you have assemblies `WNanoF.fa` and `CRRNanoF.fa` and a reference genome `reference.fasta`, please run Quast as following:
`python quast.py --threads 4 WNanoF.fa CRRNanoF.fa -r reference.fasta` (you can use `icarus.py`, too but it actually runs `quast.py` inside).

The resulting Icarus viewers can be accessed via `quast_results/latest/icarus.html`. 

Please feel free to reopen the issue and ask me any questions!
