### ISSUE TITLE
assembly.used_snps.gz is ASCII text not gzip

### ISSUE THREAD

**Issue by dariober** [ablab/quast#111]
Hi- Thanks for the great tool! I've noticed that the output file `contigs_reports/minimap_output/assembly.used_snps.gz` is in plain ASCII text despite the suffix suggesting it is gzipped- not sure this is intentiopnal... I ran quast as: 

```
quast.py {input.fa} -o quast/{sample_id} -r {input.ref} --features {input.gff} --threads 12 --fragmented
```

Check file type of `assembly.used_snps.gz`:

```
file quast/catarina1/contigs_reports/minimap_output/assembly.used_snps.gz 
quast/catarina1/contigs_reports/minimap_output/assembly.used_snps.gz: ASCII text
```

Version:

```
quast.py -v
QUAST v5.0.2
```

**Comment by alexeigurevich** [comment]
This file is always in the plain text format, never gzipped actually. However, if `--no-gzip` is not specified, `.gz` extension is erroneously added to the file name. Fixed now.
