### ISSUE TITLE
Different database for busco

### ISSUE THREAD

**Issue by mariosagb** [ablab/quast#115]
Dear developers,
I would like to ask if it is possible to use a different database, instead of eukaryotic, prokaryotic and fungal in order to run Busco. If it is possible, how can we do that? Thank you in advance.

Kind regards,
Marios

**Comment by almiheenko** [comment]
Dear Marios,

We plan to add an option to use a custom Busco database in the upcoming QUAST release. Now you can do the following thing. Please substitute the file <quast_dir>/quast_libs/run_busco.py with the attached file. Then you should edit this file. Find the line `custom_db = "BUSCO_DB_PATH"` and replace BUSCO_DB_PATH with a path to your Busco database, e.g. "/Users/marios/tools/busco/fungi". Please note that it should be a path to the unpacked Busco database.

Please let me know if you have any issues or if this method is not suitable for you.

[run_busco.py.zip](https://github.com/ablab/quast/files/3782968/run_busco.py.zip)

**Comment by mariosagb** [comment]
Thank you for your quick response!
Finally, I would like to ask what is the option I should add instead of --eukaryote in order to run busco with my database.
Thank you very much.

**Comment by mariosagb** [comment]
Thank you for your quick response!

I am glad to inform you that I managed to run quast with the busco database of my choice. Although, inside the **busco_stats directory** only **run_assembly.log** and **short_summary_assembly.txt** were created and there is not **run_assembly directory** like the way it is written in the last line of run_assembly.log:
`Results written in /home/marios/Downloads/data/quast_ref/output/busco_stats/run_assembly/. `

The method you suggested was easy enough to be performed. 

Also, I would like to provide you with all the busco datasets: https://busco.ezlab.org/frame_wget.html

**Comment by mariosagb** [comment]
This is the content of short_summary_assembly.txt:
```
# BUSCO version is: 3.0.2
# The lineage dataset is: diptera_odb9 (Creation date: 2016-02-13, number of species: 25, number of BUSCOs: 2799)
# To reproduce this run: python /opt/quast-5.0.2/quast.py -i /home/.... etc
#
# Summarized benchmarking in BUSCO notation for file /home/marios/Downloads/data/... etc
# BUSCO was run in mode: genome

        C:98.7%[S:98.2%,D:0.5%],F:0.8%,M:0.5%,n:2799

        2763    Complete BUSCOs (C)
        2748    Complete and single-copy BUSCOs (S)
        15      Complete and duplicated BUSCOs (D)
        21      Fragmented BUSCOs (F)
        15      Missing BUSCOs (M)
        2799    Total BUSCO groups searched
```
so I believe it is the correct output.
Thank you for your help.
