### ISSUE TITLE
Confusing output

### ISSUE THREAD

**Issue by Stef-cr** [ablab/quast#116]
Dear community, 
I've run Quast in order to evaluate a fungal assembly. My question is: why the total of contigs (694) is lower than all the listed contigs (1741, sum up from all the #contig length)? Can someone help please?

As follows the code I used and output

$ quast.py -o B0_QV30 --threads 6 -r /pub39/ext/stefany/COSTA_RICA/Bauveria/Stef_temporal/UCR/Bbas.fasta -g /pub39/ext/stefany/COSTA_RICA/Bauveria/Stef_temporal/UCR/Bbas.gff -e --fungus -k --k-mer-stats -f --gene-finding --pe1 /pub39/ext/stefany/COSTA_RICA/Bauveria/Stef_temporal/UCR/B0_R1_paired.fastq --pe2 /pub39/ext/stefany/COSTA_RICA/Bauveria/Stef_temporal/UCR/B0_R2_paired.fastq /pub39/ext/stefany/COSTA_RICA/Bauveria/Stef_temporal/UCR/spades_assembly_B0_trimmed_30/scaffolds.fasta

My output:
##########
All statistics are based on contigs of size >= 500 bp, unless otherwise noted (e.g., "# contigs (>= 0 bp)" and "Total length (>= 0 bp)" include all contigs).

Assembly                       scaffolds        
# contigs (>= 0 bp)            1249             
# contigs (>= 1000 bp)         499              
# contigs (>= 5000 bp)         296              
# contigs (>= 10000 bp)        263              
# contigs (>= 25000 bp)        225              
# contigs (>= 50000 bp)        188              
Total length (>= 0 bp)         33228498         
Total length (>= 1000 bp)      32919000         
Total length (>= 5000 bp)      32484156         
Total length (>= 10000 bp)     32257657         
Total length (>= 25000 bp)     31622371         
Total length (>= 50000 bp)     30260036         
# contigs                      694

**Comment by alexeigurevich** [comment]
This is related to the "# contigs" and "# contigs (>= X bp" definition. 
The difference is explained in details in [Q11 in the FAQ section of our online manual](http://quast.sourceforge.net/docs/manual.html#faq_q11).
