### ISSUE TITLE
The same number of misassemblies after adding ONT long reads

### ISSUE THREAD

**Issue by hd00ljy** [ablab/quast#118]
Hello

  I am examining my assembly generated from ONT long reads using WTDBG2.

  **I want to exclude the true SVs from the misassemblies count but I have trouble in doing that**.

  1. At first, I got 543 misassemblies in 361 contigs out of 3466 contigs in total

     This is the command I run
```

 time quast.py -t 28  ctg.fa \
               -r Homo_sapiens_assembly38.main.fasta \
               -g gencode.v32.chr_patch_hapl_scaff.basic.annotation.gff3 \
         -l "WTDBG2" \
         --eukaryote \
         --large \
         --k-mer-stats \
         --circos \
         --min-identity  90.0
```

  2.  To exclude structural variations from these misassemblies,  I added raw reads.
      But I got the same number of misassemblies(543) in the same number of contigs(361)

      - I used the same reads from which I generated the assembly

      - I was able to see read-level QC reports not shown in the previous run.

      - This is the command I used
```

time quast.py -t 28  ctg.fa \
               -r Homo_sapiens_assembly38.main.fasta \
               -g gencode.v32.chr_patch_hapl_scaff.basic.annotation.gff3 \
         -l "WTDBG2" \
         --eukaryote \
         --large \
         --k-mer-stats \
         --circos \
         --min-identity  90.0 \
         --nanopore  ont_reads.fastq
```

  **Did I do something wrong or misunderstand the following documentation?**

![image](https://user-images.githubusercontent.com/13775022/69403354-b50e4980-0d3d-11ea-823b-5e7dae67178f.png)

**Comment by alexeigurevich** [comment]
Hello,
You did everything right but Quast currently supports SV-detection only based on Illumina short paired-reads, as we rely on [GRIDDS](https://github.com/PapenfussLab/gridss) for this task and it can operate with Illumina data only. ONT reads are supported by Quast in general but are used only for reporting read stats (as you noticed) and for generating Upper Bound Assembly (if `--upper-bound-assembly` is specified, see details in the manual and in [Mikheenko et al, 2018](http://dx.doi.org/10.1093/bioinformatics/bty266)).
We are thinking about adding long read-based SV detection in the future but it is not in the near future plans.
