### ISSUE TITLE
metaQUAST error

### ISSUE THREAD

**Issue by shaman-narayanasamy** [ablab/quast#12]
Hi,

MetaQUAST seems to be terminating on one of the downloaded references. Below is the error I am getting:

`'Escherichia_coli_O104_H4_str_2009EL-2071' Traceback (most recent call last):   File "/usr/bin/metaquast", line 730, in <module>     return_code = main(sys.argv[1:])   File "/usr/bin/metaquast", line 635, in main     
num_notifications_tuple=total_num_notifications)   File "/usr/bin/metaquast", line 158, in _start_quast_main     return_code = quast.main(args)   File "/home/imp/lib/quast-release_3.1/quast.py", line 692, in main     ref_fpath, contigs_fpaths, qconfig.prokaryote, os.path.join(output_dirpath, 'contigs_reports'), old_contigs_fpaths)   File "/home/imp/lib/quast-release_3.1/libs/contigs_analyzer.py", line 1525, in do     for i, fname in enumerate(zip(contigs_fpaths, old_contigs_fpaths)))   File "/usr/lib/pymodules/python2.7/joblib/parallel.py", line 517, in __call__     self.dispatch(function, args, kwargs)   File "/usr/lib/pymodules/python2.7/joblib/parallel.py", line 312, in dispatch     job = ImmediateApply(func, args, kwargs)   File "/usr/lib/pymodules/python2.7/joblib/`

Let me know if you need more information. Looking forward to your response.

-Shaman-

**Comment by almiheenko** [comment]
Hi Shaman,

Could you try to use the last version of QUAST (3.2)? If this problem persists, please, send metaquast.log and quast.log to quast.support@bioinf.spbau.ru.
