### ISSUE TITLE
Can I only run "Statistics without reference"?

### ISSUE THREAD

**Issue by PandengWang** [ablab/quast#122]
Thanks for providing this useful tool!
It costs too much time to run all the analyses.
I only want to get the resutls about "Statistics without reference". 
Is it possible to skip all the reference-related analyses?

Best regards,
Pandeng

**Comment by alexeigurevich** [comment]
Thanks!
The solution to your problem is very easy. Just do NOT specify a reference genome (`-r` option) and Quast will compute only "Statistics without reference" in this case.
