### ISSUE TITLE
Quast 5.0.2: BUSCO DBs download fail

### ISSUE THREAD

**Issue by ptrebert** [ablab/quast#124]
Hi,
in a fresh Conda environment with only `quast=5.0.2`, `busco=4.0.2` and `augustus=3.3.3`, running the command `quast-download-busco` downloads only the Augustus database successfully. The BUSCO databases fail with the message "HTTP Error 301: Moved Permanently", which seems to be a known/re-occurring problem (see #65). A simple `wget` call with the given URL works fine, and shows that the domain changed from `busco.ezlab.org/` to `busco-archive.ezlab.org`.

Apart from the above, it would be helpful if `quast-download-busco` would exit with a non-zero code if the database download fails; this would simplify unsupervised and automatic environment setups.

Best,
Peter

**Comment by javijevi** [comment]
I have the same error. I'd say that it's due to QUAST trying to download the odb9 version of the BUSCO database, whereas I think the BUSCO guys have upgraded to odb10 and eliminated the odb9 links which QUAST tries (e.g., https://busco.ezlab.org/v2/datasets/bacteria_odb9.tar.gz).

Any workaround to this?

Cheers,
Javier.

**Comment by alexeigurevich** [comment]
The workaround is to use the latest pre-release [Quast 5.1.0rc1](https://github.com/ablab/quast/releases/tag/quast_5.1.0rc1) -- the BUSCO issue is fixed there. As soon as we will release a mature version 5.1.0, we will add it to `conda` as well.

**Comment by splaisan** [comment]
Hi, 
I have the same while installing `metaWrap` and do not dare to upgrade busco risking to break metawrap.
if @[ptrebert](https://github.com/ptrebert) is right, would it please be possible to change the code of `quast-download-busco `to point to the right URL.
I see that the url in not hardcoded in that script and do not know where to edit myself.
thanks in advance
