### ISSUE TITLE
ERROR:because it contains non-ACGTN characters

### ISSUE THREAD

**Issue by Salonee-123** [ablab/quast#127]
Hi,
As input I had given  NOVOPlasty output option assmebly file with reference chloroplast genome to check the assembly. After giving the command it is showing the message 'skipping the file as it contains non-ACGTN characters'. later i had checked and found that in the beginning it contains W at some places. Although I can't scan the whole contig manually for non ACGTN bases, i want to know the solution to this problem. How these non-ACGTN bases can be removed or sorted out so that i can run QUAST for evaluating the assemblies.

**Comment by lovishpuri** [comment]
What's W, why it is present ?  Please read about [MCVE](https://stackoverflow.com/help/minimal-reproducible-example). Clearly, this is not an issue with Quast
