### ISSUE TITLE
Move downloads from sourceforge to github

### ISSUE THREAD

**Issue by michaelbarton** [ablab/quast#13]
Quast takes quite a long time to download from sourceforge, approximately ~7 minutes. Would you consider moving the releases to github using their release feature? I think this might provide faster access. I ask because [creating a Docker container of quast](https://github.com/bioboxes/quast) requires downloading this file each time, which makes the process take a long time as a whole.

Also would you consider releasing .xz versions too, to further decrease the file size?

Thank you.

**Comment by alexeigurevich** [comment]
Hi Michael,

We published new release at both sourceforge (as usual) and at github (see https://github.com/ablab/quast/releases/tag/release_4.0) as you suggested!

**Comment by michaelbarton** [comment]
Thanks Alex. This is a much faster download. I'll look into updating the the bioboxes/quast Docker image with this new version.
