### ISSUE TITLE
No. of misassemblies - what is a good threshold?

### ISSUE THREAD

**Issue by noahaus** [ablab/quast#130]
Greetings,

I wanted to get the community input on how many misassemblies for a bacterial genome assembly are acceptable, and a paper that discusses why the number of misassemblies is okay? I am using pair read data to assemble bacterial genomes and everything works fine, but I am trying to wrap my head on how to interpret the QUAST stats that deal with misassembles.

The distribution of my assemblies:
![image](https://user-images.githubusercontent.com/40697188/75178925-034d3300-5707-11ea-89fd-91911f6b5f17.png)

Any help is greatly appreciated!

**Comment by asl** [comment]
Hello

There is no silver bullet / gold threshold here. As there are many reasons of misassemblies (including valid difference wrt the reference due to e.g. transposons) and many usages of these contigs.

**Comment by noahaus** [comment]
Great! So as long as the numbers aren't excessively high, I can still have confidence in the results. I appreciate the response and will close the issue.
