### ISSUE TITLE
Is it possible to separate out Icarus/Circos plots generation to a separate command?

### ISSUE THREAD

**Issue by SHuang-Broad** [ablab/quast#133]
They are single threaded and take really long time.

So I am wondering if it is possible to separate out a different command for making these plots.

Based on `quast.py`, it is only going to affect the html report, and quite possibly only in a such a way that hyperlinks to the Viewers will not be available. This seems to be a small price to pay. The benefit is that it allows running quast in automated ways (no human need to ctrl-c), and better parallarization.

Thanks.

**Comment by SHuang-Broad** [comment]
This default behavior of running the plots is forcing us to wait.
Force stopping the program unfortunately will also stop the production of `report.pdf`, which we need.

So a minimal fix could be move the generation of `report.pdf` before the Icarus/Circos plots steps.

Thanks.

**Comment by alexeigurevich** [comment]
Dear @SHuang-Broad,
Am I understand you correctly that you just don't want Circos and Icarus to be generated? In this case, there is a quick workaround even in the current version (5.0.2), see [online manual](http://quast.sourceforge.net/docs/manual.html) for more details:
1. Circos is generated only if `--circos` option is specified, so to disable it creation just skip this option.
2. You can skip Icarus viewers generation by specifying `--no-icarus` option. In this case, all other HTML reports will be created as usual. Note that you can also skip all HTMLs generation by using `--no-html` but the rest reports are pretty fast to create.

However, if you want a separate command/utility that takes a completed Quast output directory and just creates Circos and Icarus there, it would be more difficult to implement (albeit also possible in the future). 
Anyway, your suggestion about changing the order of report.pdf/Icarus/Circos totally makes sense, I've just implemented it in the master branch. The fix would be available in the upcoming release (~5.1.0, no tentative release date yet).

Please close the issue if you think it is resolved now or comment if something is still needed (e.g. I understood your query incorrectly).

**Comment by alexeigurevich** [comment]
Closing the issue since [5.1.0 release candidate](https://github.com/ablab/quast/releases/tag/quast_5.1.0rc1) with this fix is available now

**Comment by SHuang-Broad** [comment]
Thanks for implementing this Alex!
