### ISSUE TITLE
"IOerror: [errno 36] file name too long"

### ISSUE THREAD

**Issue by dmacguigan** [ablab/quast#135]
Hello,

I am attempting to run QUAST with conserved gene finding. I am using the following options

quast.py ../../10x-NanoporeHybrid/v0.1/Eper_nanopore_500bp.racon.pilon_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds.fa.gz \
-r ../../10x-NanoporeHybrid/v0.1_quickmerge/merged_Eper_10x-nanopore_quickmerge.fasta.gz --threads 20 \
--split-scaffolds --eukaryote --large --k-mer-stat --conserved-genes-finding --plots-format pdf 

Unfortunately, I have encountered an unhandled exception from BUSCO: "IOerror: [errno 36] file name too long"

I have attached the log files. Thank you in advance.

[run_Eper_nanopore_500bp-racon-pilon_c5_m50_10000_s98_r0-05_e30000_z500_l5_a0-3-scaffolds.log](https://github.com/ablab/quast/files/4395855/run_Eper_nanopore_500bp-racon-pilon_c5_m50_10000_s98_r0-05_e30000_z500_l5_a0-3-scaffolds.log)
[run_Eper_nanopore_500bp-racon-pilon_c5_m50_10000_s98_r0-05_e30000_z500_l5_a0-3-scaffolds_broken.log](https://github.com/ablab/quast/files/4395856/run_Eper_nanopore_500bp-racon-pilon_c5_m50_10000_s98_r0-05_e30000_z500_l5_a0-3-scaffolds_broken.log)

**Comment by alexeigurevich** [comment]
BUSCO appends many suffixes/prefixes to original filenames making it larger and also uses a nested set of folders, so in some rare cases, the absolute path to a file could become so large that your operating system cannot handle it (there is usually a limit on filename length). So, I would suggest to rename (or symlink) your filename `Eper_nanopore_500bp.racon.pilon_c5_m50-10000_s98_r0.05_e30000_z500_l5_a0.3.scaffolds.fa.gz` to something shorter, e.g. `scaffolds.fa.gz` and try again. 

I will close the issue, please reopen if the problem persists.
