### ISSUE TITLE
AttributeError: module 'cgi' has no attribute 'escape' on Python 3.8.0

### ISSUE THREAD

**Issue by bagashe** [ablab/quast#140]
cgi.parse has been removed in version 3.8. `html.escape` is the suggested replacement.

**Comment by bagashe** [comment]
Looks like this is fixed in master. Looking forward to the next release. Thanks for working on this great tool.

**Comment by alexeigurevich** [comment]
Thanks!
Note that we have a [pre-release](https://github.com/ablab/quast/releases/tag/quast_5.1.0rc1) with this fix included, hopefully it will be transformed into a stable release soon.
