### ISSUE TITLE
Generate HTML report separately

### ISSUE THREAD

**Issue by reinator** [ablab/quast#146]
Hi!

Is it possible to generate the HTML reports and Icarus viewer using the results obtained previously?

Thanks!

**Comment by alexeigurevich** [comment]
Hi!

Unfortunately, it is not possible now. The only thing you can do is to rerun Quast with the same command on the same output folder and _some_ already computed results (e.g. contig alignments) will be reused while some others will be recomputed. So, in summary it will be faster than running Quast from scratch but still would take non-trivial time. 

At the same time, we are aware of this issue (and [this](https://github.com/ablab/quast/issues/132) related one) and hope to make a better workaround soon.

**Comment by PlekhanovaElena** [comment]
I am out of the office from Wed 22.07.2020 until Sun 16.08.2020.
 
Dear Mailer, I am doing my fieldwork and then have a week of vacation until 16th of August 2020. Please note, that I don't have internet on my field work site, so would not receive your message until I'm back.
Thank you for your understanding :)


Best wishes,
Elena Plekhanova

**Comment by reinator** [comment]
Good to know that if I run with the same conditions, Quast will try to use the completed stages.
Thanks a lot! 

A solution that I had found was to use MultiQC to generate some basic reports using QUAST output.
Still, when QUAST get this functionality, it will be awesome. 

I will close this issue for now.
