### ISSUE TITLE
Feature Request: get files containing plot data

### ISSUE THREAD

**Issue by Myskmadra** [ablab/quast#149]
Hey,

I am using quast to get assembly stats from routinely assembled genomes and I would like to include it in an automated workflow. In the end, I would like to display the results in my own frontend ui and it would be of great help to have the actual data for the plots available in order to be able to re-plot it. I could probably extract the data somehow from the files created but would it be possible to maybe generate tsv/csv files containing the data for the plot?

**Comment by alexeigurevich** [comment]
Hi, 
You can try to use `-j` (or `--save-json`) option to retrieve plots source data in JSON format. This option is intended for developers only, so it is "hidden" (not shown in `--help` menu). However, feel free to use it if it helps in your task.

Example:
`> ./quast.py -r test_data/reference.fasta.gz test_data/contigs_1.fasta --save-json`
```
> ls quast_results/latest/json/
assemblies.json		broken_scaffolds.json	contig_size_html.json	coordNAx.json		coordNGx.json		coordmisassemblies.json	data_sizes.json		icarus.json		ms_selector.json	ref_name.json		report.json
assemblies_lengths.json	colors.json		contigs_lengths.json	coordNGAx.json		coordNx.json		data_alignments.json	gc.json			menu_reference.json	ref_length.json		reference.json		tick_x.json
```

**Comment by Myskmadra** [comment]
awesome! Looks like what I needed! Cheers @alexeigurevich
