### ISSUE TITLE
 import joblib ModuleNotFoundError: No module named 'joblib 

### ISSUE THREAD

**Issue by ajkarloss** [ablab/quast#152]
Hi, I am using quast@5.0.2 in Galaxy 19.05. I am getting the same error as mentioned. I have installed joblib using conda. But still the same error. Any tips?

**Comment by alexeigurevich** [comment]
I suppose that you have several versions of Python on your machine. The default one is probably used for running Quast and it is missing joblib. Another version is managed by conda and you installed joblib there. Please try to run Quast using this conda Python.
You may check the default version of Python by running `which python` in your terminal. The default python is usually located in `/usr/bin/python`. Conda python is usually installed in something like `~/miniconda3/bin/python` (or `~/miniconda2/bin/python`).
You can use the full path to the desired interpreter in front of Quast command like this:
`~/miniconda3/bin/python <your_quast_installation_dir>/quast.py  <other params and arguments>`.

Let me know if it does not work for you! Also, please attach quast.log file in this case.
