### ISSUE TITLE
AttributeError: module 'cgi' has no attribute 'escape' on python v. 3.8.5

### ISSUE THREAD

**Issue by albaguillen13** [ablab/quast#159]
Hi! 

I got this error while running quast.py, I'm new in this so, where is the trouble? I've attached the quast.log file

Thank you,
A
[quast.log](https://github.com/ablab/quast/files/5913618/quast.log)

**Comment by zwets** [comment]
See #157.

**Comment by albaguillen13** [comment]
> See #157.

Thank you for you quick response ! I've fixed the error.
