### ISSUE TITLE
Display physical coverage in Icarus in addition to reads coverage

### ISSUE THREAD

**Issue by alexeigurevich** [ablab/quast#16]
Physical coverage is the coverage of the reference by the paired-end fragments, counting the reads and the gap between the paired-end reads as covered. This additional track may be useful in identifying reference misassemblies and read coverage gaps that cannot be scaffolded over due to a lack of physical coverage.

While the definition above is rather obvious it is not clear how to calculate per-base physical coverage in many practical cases. For example, we should decide what to do with orphan reads, reads mapped with insert size much larger than average one and so on. 
Some discussions on this are here: https://www.biostars.org/p/131268/

This enhancement idea was suggested by @sjackman (Shaun Jackman)

**Comment by sjackman** [comment]
> Could you explain use cases where physical coverage track will be useful?

When a contig/scaffold ends or is misassembled, physical coverage helps troubleshoot whether the assembly, the reads, or the reference assembly is to fault.

When a region has no read coverage but does have physical coverage, it indicates a region where the assembly cannot assemble a contig, but should be able to scaffold over.

If a region has low/no read coverage and low/no physical coverage, it indicates a region where the assembly does not expect a contig nor scaffold.

If a region has typical read coverage but has low physical coverage, it can indicate a region of reference misassembly.

**Comment by sjackman** [comment]
> Should we consider single reads or improperly paired reads somehow? 

Single reads and improperly paired reads should be ignored in physical coverage calculation.

Reads pairs for which both reads are multimapped, can be useful to either count or ignore depending on the situation. Ignoring them is useful to indicate genomic positions where scaffolds should end, because the repeat at that position is larger than the sequencing fragment size.

**Comment by sjackman** [comment]
> Should we check insert size deviation somehow and, e.g. skip remotely mapped reads? 

Filtering out improperly paired reads should be good enough, as long as that flag is set. Super long incorrectly paired fragments could possibly dominate the physical coverage count if not filtered out.

**Comment by sjackman** [comment]
> How do you calculate physical coverage usually? samtools/bedtools/some ad hoc script?

Filter as above, create a BED file of (read start pos, read start pos + isize) and use `bedtools genomecov`.

**Comment by alexeigurevich** [comment]
We added physical coverage to coverage track. @sjackman, please take a look at the attached example and feel free to checkout the latest source code. We are waiting for your comments :)
[alignment_viewer.html.zip](https://github.com/ablab/quast/files/319208/alignment_viewer.html.zip)

Note that we calculate physical coverage as you suggested (extracting properly paired reads and counting the gaps between the paired-end reads and reads itself as covered fragments). If you find this feature useful in some cases, please send us few examples -- it will be very interesting to look at them!.

**Comment by sjackman** [comment]
Thanks! I'll test it out and get back to you. In the example I notice that there are spots were read coverage drops quickly but it is smoother in physical coverage. That's a good example of why scaffolding works, because there are positions with poor read coverage, but still spanned by paired-end reads.
