### ISSUE TITLE
QUAST report

### ISSUE THREAD

**Issue by rthapa1** [ablab/quast#160]
Hi, I have a question about QUAST report. I want to see the quality of the assembly. The total length of the genome is 3840000. The total length of the assembled genome is 3817372. It shows that the length of misaligned contig length is 3797080. Does it mean that the assembly is not good? Could you please check the attached QUAST report and let me know if the assembly is good? Thanks

Assembly                     query.contigs
contigs (>= 0 bp)          2             
contigs (>= 1000 bp)       2             
contigs (>= 5000 bp)       2             
contigs (>= 10000 bp)      2             
contigs (>= 25000 bp)      2             
contigs (>= 50000 bp)      2             
Total length (>= 0 bp)       3855491       
Total length (>= 1000 bp)    3855491       
Total length (>= 5000 bp)    3855491       
Total length (>= 10000 bp)   3855491       
Total length (>= 25000 bp)   3855491       
Total length (>= 50000 bp)   3855491       
contigs                    2             
Largest contig               3797080       
Total length                 3855491       
Reference length             3833832       
GC (%)                       53.57         
Reference GC (%)             53.58         
N50                          3797080       
NG50                         3797080       
N75                          3797080       
NG75                         3797080       
L50                          1             
LG50                         1             
L75                          1             
LG75                         1             
misassemblies              13            
misassembled contigs       1             
Misassembled contigs length  3797080       
local misassemblies        23            
scaffold gap ext. mis.     0             
scaffold gap loc. mis.     0             
unaligned mis. contigs     0             
unaligned contigs          0 + 1 part    
Unaligned length             35381         
Genome fraction (%)          99.054        
Duplication ratio            1.006         
N's per 100 kbp            0.00          
mismatches per 100 kbp     126.92        
indels per 100 kbp         423.59        
Largest alignment            972164        
Total aligned length         3817372       
NA50                         584494        
NGA50                        584494        
NA75                         251449        
NGA75                        251449        
LA50                         3             
LGA50                        3             
LA75                         6             
LGA75                        6

**Comment by alexeigurevich** [comment]
Hi!
There is no clear criterium which assembly should be considered "good" or "bad". It all depends on your need for further analysis of the sequence. E.g. for some tasks having as few misassemblies as possible is critical while in other applications the most important parameter is Genome Fraction, etc.

Your assembly consists of just 2 contigs, one is 3797080 bp long and another one is just 3855491-3797080=58411 bp long. As long as there is at least one misassembly in a contig, it is considered by Quast as a "misassembled contig". Misassembled contigs length is just the total length of all misassembled contigs. This parameter does not take into account whether the misassemblies inside are large or small or whether they are located in the same small region (e.g. on the edge of a contig) or uniformly distributed across the entire contig (which is worse). So, don't be too afraid of having so large Misassembled contigs length. To check this, you should look at misassembly locations by eye in the Icarus contig browser (could be opened from report.html).

A few other hints:
> Genome fraction (%) 99.054  

This is a rather good value

> mismatches per 100 kbp 126.92

This is often too large for short-read assemblies but may be the case for assemblies from noisy long reads with relatively bad per-base quality. But, once again, it depends on your further needs, whether you need high per-base quality or not.

Also, note that sometimes "bad" metric values may be true discrepancies between the sequenced organism (and thus its assembly) and your reference genome which may e.g. represent another strain of the same species.

**Comment by npawarut** [comment]
@alexeigurevich Could you please give some examples of the effects of misassemlies/mismatch on downstream analysis?
