### ISSUE TITLE
Syntax Error:Invalid Syntax

### ISSUE THREAD

**Issue by hchetia** [ablab/quast#178]
Hi I am getting the following error running quast on my de novo genome assembly from abyss-pe.
 >6 3148 40663 read:A00815:188:H55YWDRXY:1:2101:25238:1391/1
    ^
SyntaxError: invalid syntax
How can I resolve this?
Best,
Hasna

**Comment by alexeigurevich** [comment]
Hi Hasna,
It seems that you are providing Quast with a wrong file. An assembly should be in the FASTA format, i.e., looks like
>Contig_name
ACGT...
ACGTNNNACGT..
>Another-contig
ACGT...

**Comment by hchetia** [comment]
Hi @alexeigurevich 
I am using a .fasta format assembly.
Here is a head of the file

>6 3148 40663 read:A00815:188:H55YWDRXY:1:2101:25238:1391/1
CTGGCTCTGTCGCCTAGGCTGGAGTGCAGTGGCTCGATCTCAGCTCACTGCAAGCTCCGCTCCCTTGGTTCATGCCATTCTCCTGCCTCAGCCTCCGGAGTAGCTGGGAACACAGGCGCCCACCACTACACCCGGCTAATTTTTTTGTGTATTTAGTAGAGACGGGGTTTCACTGTGTTAGCCAGCATGGTCTCCATCTCCTGACCTCGTGATCCACCTGCCTCGGCCTCCCAAACTGCTGAGATTACAGGCGTGAGCCACCGCGCCCAGCCCAAAATAAGTTTATATCAAATCCGGCTTCCAGAAATGGTAGTAGTTAAGCACATCAATTTACCATGTAAATCATTCACTTGTACCAATGGGGAAAATTTATTGTTATTGTGCTTCACAGTGAAAACAAGAATAATCTTTCATTTTTAAAAATTAATTTAGGAAAGATTACATAACTTGGCCCTTTAGTATGTATACAGTAGCACTAGTTTATACACTACTTTTGCCACTGGGGAGTTTCAGTTAAAACATCCCTCAGTCATATAGCTATGGAATGCATCTTCCATTTATAATTTCTGCACTAATAATTAGTTTGGATCAAAGTTATTTTTATATATACTACAAAACAAAAGCAAACTAGTCCACCTTAAATTTTTATGTTTAGAATTTTCTATATGTAAATCATTCAGATTAGTATCTATGTAGGTTCAGTCAAATCCAACCACGGATTTGAGTTATTATACTATATAACCCTGTAAGATACATAGAAATGTTGTTACTTTGCCTTTATAACAGAACCAAAGTGTCTGTTTCAATTTATAAATTCAGCATTTGAGTAACTTTGATTCCCAAAATTAGGAGAAAATAACAAAATAATGAGAAGGG

Do you think the header file is incompatible with quast? If yes, how can I resolve this?

**Comment by almiheenko** [comment]
Hi Hasna,

Quast should work well with this file. Could you please attach the `quast.log` file from the failed run?

**Comment by hchetia** [comment]
Hi @almiheenko 
Actually there was a mistake from my side in the script.
QUAST is running fine.
Thanks,
Hasna
