### ISSUE TITLE
ERROR! exception caught!

### ISSUE THREAD

**Issue by Lewis2020JPG** [ablab/quast#181]
According to the installation process on the official website, this error was found during the test.

My test.sh is like this:
`python ./software/quast/quast-5.0.2/quast.py contigs_1.fasta contigs_2.fasta -t 8 -o quast`
Here is the log:
[quast.log](https://github.com/ablab/quast/files/7070749/quast.log)

I didn't find any solution for my problem. Please help me. Thank you very much!

**Comment by alexeigurevich** [comment]
This is a known issue of 5.0.2 release when used with python 3.8 and above.
Please check out https://github.com/ablab/quast/issues/157 for more details and workarounds.
