### ISSUE TITLE
Is it possible to get tsv output for stuff like NA50 and N50

### ISSUE THREAD

**Issue by Unaimend** [ablab/quast#183]
I would like to know if there is an easy way to get the quast output for all reported quast statistics? Because atm. I can only see NGA50 being output.

**Comment by alexeigurevich** [comment]
There is always `report.tsv` in the output directory which contains exactly the same stats as regular `report.txt` and is pretty similar to what we provide in `report.html`. Or do you mean something else, e.g. (x,y) coordinates for the NGAx plot? This is not available yet but we think of adding it later.

**Comment by Unaimend** [comment]
I cant seems to find the report.tsv you mentioned
This is the content of my output folder
![image](https://user-images.githubusercontent.com/7808379/132028609-1b28d6b9-38d6-4822-8e5d-368bbec3a5b6.png)
This is how I started quast
![image](https://user-images.githubusercontent.com/7808379/132028666-eb5da7ac-82e1-4950-81b1-afb615382892.png)
And thats my summary folder
![image](https://user-images.githubusercontent.com/7808379/132028907-432fe9f7-f269-4f82-9fdc-55eb0acdf4de.png)

**Comment by alexeigurevich** [comment]
Ahh, this is metaQUAST, this confused me at first :) 
In regular QUAST you get both `report.txt` and `report.tsv`, while in metaQUAST only `report.html` is present on the top level and you can find the TXT and TSV versions only inside `combined_reference` and `run_per_reference` subdirectories.

To add new summary reports like `NGA50.tsv`, you need to add them to the list of `main_metrics` in `<quast_installation_dir>/quast_libs/reporting.py` 
See https://github.com/ablab/quast/blob/master/quast_libs/reporting.py#L288  
The more or less complete list of all Quast metrics seems to be `order` in the same file (see https://github.com/ablab/quast/blob/master/quast_libs/reporting.py#L199 ). If you want ALL metrics to be reported in such a summary TSV file, I think you can simply skip "NAME, CONTIGS__FOR_THRESHOLDS, TOTALLENS__FOR_THRESHOLDS" from `order` and copy the rest to the `main_metrics` content.
