### ISSUE TITLE
Conda Prompt Unsatisfiable error

### ISSUE THREAD

**Issue by BrnToCode** [ablab/quast#184]
I used this command to install mysql connector but there is a issue occuring in the prompt ,Can anyone tell me how to resolve the issue???

>>conda install -c anaconda mysql-connector-python

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.-
Examining @/win-64::__win==0=0:  20%|██████████▍                                         | 1/5 [00:01<00:07,  2.00s/it]|                                                                                                                       \failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - mysql-connector-python -> python[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.When python appears to the right, that indicates that the thing on the left is somehow not available for the python version you are constrained to. Note that conda will not change your python version to a different minor version unless you explicitly specifythat.

**Comment by asl** [comment]
Not connected to quast
