### ISSUE TITLE
IndexError: list index out of range + CIRCexplorer2 parse

### ISSUE THREAD

**Issue by BirongZhang** [ablab/quast#186]
Hi all,

Thanks for developing such a useful software！

I used STAR aligners to get the Chimeric.out.junction file. But in the next steps_Parsing for Circular RNA Fusion Junction Reads, I ran into some problems: 

Here is my command and error:
<img width="775" alt="Screenshot 2021-10-07 at 23 42 34" src="https://user-images.githubusercontent.com/74430395/136472091-95f12e86-9822-4caf-89eb-00cb1fd29f42.png">

Here is my CIRCexplorer2_parse.log:
<img width="609" alt="Screenshot 2021-10-07 at 23 43 30" src="https://user-images.githubusercontent.com/74430395/136472173-30f342e1-ac5c-4502-96a6-b3c9777ef727.png">

Here is my Chimeric.out.junction file:
<img width="634" alt="Screenshot 2021-10-07 at 23 45 40" src="https://user-images.githubusercontent.com/74430395/136472390-0c85b38d-b30b-44c1-8160-573dbb39e558.png">

Any advice would be appreciated. Thanks.

**Comment by alexeigurevich** [comment]
Sorry, we are not the authors or maintainers of CIRCexplorer and STAR, please contact them to get support.
