### ISSUE TITLE
error running gmes_petap.pl

### ISSUE THREAD

**Issue by guptapa** [ablab/quast#190]
Hi,
I am getting following error reported in std out file while running this script:
/home/genome/augustus_training/braker/dependencies/gm_et_linux_64/gmes_petap.pl --verbose --cores=60 --sequence=genome.fasta  --ET=introns.f.gff

Error in out file:
check before run
create directories
commit input data
data report
commit training data
training data report
prepare initial model
get GC of sequence
GC 44
build initial ET model
error, no valid sequences were found
error on call: /home/genome/augustus_training/braker/dependencies/gm_et_linux_64/make_nt_freq_mat.pl --cfg /augustus_training/run.cfg --section donor_GT    --format DONOR 

look at gems.log file attached.
Need help!

Thanks,
Parul
[gmes.log.docx](https://github.com/ablab/quast/files/7455112/gmes.log.docx)

**Comment by alexeigurevich** [comment]
Hi, this issue seems to be unrelated to Quast. Could you try to reach out the augustus developers instead?
