### ISSUE TITLE
Origin of unaligned bases

### ISSUE THREAD

**Issue by jowong4** [ablab/quast#192]
My quast report informs me that I have unaligned bases in my contigs. I would like to know how to locate these contigs.

**Comment by alexeigurevich** [comment]
To find the list of fully unaligned contigs, please check out `<quast_output_dir>/contigs_reports/minimap_output/<your_assembly_name>.unaligned`

To find partially unaligned contigs and coordinates of the unaligned fragment, please look for "This contig is partially unaligned" in `<quast_output_dir>/contigs_reports/contigs_reports_<your_assembly_name>.stdout` (this file also contains fully unaligned contigs labelled with "This contig is unaligned")

Also, you can visually inspect unaligned and partially unaligned contigs in the Icarus browser. Just open `<quast_output_dir>/icarus_viewers/contig_size_viewer.html` and refer to the block's color and color legend.

Not in your question, but just in case: 
To find "alignment gaps" in the reference, i.e. reference regions not covered by an assembly, please check out `<quast_output_dir>/genome_stats/<your_assembly_name>_gaps.txt`
