### ISSUE TITLE
custom contig length categories

### ISSUE THREAD

**Issue by slambrechts** [ablab/quast#196]
Hi,

Quast reports the number of contigs that are >= 50000 bp, 25000-50000 bp, 10000-25000 bp, 5000-10000 bp, and 1000-5000 bp in length. Is it possible to edit these cutoffs? e.g. I would like to know the number of contigs that are 1000-2500 bp

Kind regards,
Sam

**Comment by alexeigurevich** [comment]
Hi,

Yes, it is possible with `--contig-thresholds` option, e.g., `--contig-thresholds 1000,2500` will report the number of contigs >=1000bp and >=2500bp. Note that you should separate the desired numbers with **commas and don't use spaces** in between!

**Comment by slambrechts** [comment]
ok thank you, that worked!
