### ISSUE TITLE
Which script control the step of numcer?

### ISSUE THREAD

**Issue by lamz138138** [ablab/quast#21]
Hi!

I had evaluated my assemble with quast, but it was failed at the step of nucmer (it was kiiled). According to the log, it seemed it was killed before the step of broken the scaffold, and it was said "Analysis is finished" in the file of "nucmer_output/\*sf". Also, the "all_alignment_\*" file is empty. So I want to run step by step to find the reason, however, I can't get information about the produce of some files, such as \*headless, all_alignment_\*. After searing the script in github, I look for help here.

Any suggestion would be grateful!

Best wishes!

**Comment by alexeigurevich** [comment]
Hi!
If you are using current release version (quast-4.1) than everything regarding Nucmer and further analysis is in libs/contigs_analyzer.py. If you are using current version from master branch then everything started again in libs/contigs_analyzer.py but we made a huge refactoring there and most of the steps in this module were split into multiple units under libs/ca_utils/. For example, Nucmer-related stuff is in libs/ca_utils/align_contigs.py now.
Also you could run ./quast.py with --debug command and it will show you more details about running commands (but not all of them).

In any case, you could send us your quast.log file and may be assembly+reference genome and we can try to help you find the problem (our support email is quast.support@bioinf.spbau.ru)

**Comment by lamz138138** [comment]
Hi, alexeigurevich!

Thanks you for your reply. I only backed up the nucmer output, and the quast.log was rewrite since I re-run the pipeline. In my mind, the log that list below give little information.  I would re-run the quast.py with nucmer output and give the log latter.

I had read contigs_analyzer.py, but I can't find how "\*headless" and "alignment_\*.tsv" were created, which was needed such as in the step of show-snps. 

Any suggestion would be grateful!

The output in quast.log:

> /myPath/quast-4.1/libs/E-MEM-linux/delta-filter -i 95 -l 0 output/contigs_reports/nucmer_output/graph_prefix.scafSeq.delta \
>      > output/contigs_reports/nucmer_output/graph_prefix.scafSeq.fdelta 2> output/contigs_reports/contigs_report_graph_prefix.scafSeq.stderr
>   1  /myPath/quast-4.1/libs/E-MEM-linux/show-coords output/contigs_reports/nucmer_output/graph_prefix.scafSeq.delta \
>      > output/contigs_reports/nucmer_output/graph_prefix.scafSeq.coords_tmp 2> output/contigs_reports/contigs_report_graph_prefix.scafSeq.stderr
>   1  /myPath/quast-4.1/libs/E-MEM-linux/show-snps -S -T -H output/contigs_reports/nucmer_output/graph_prefix.scafSeq.delta \
>      < output/contigs_reports/nucmer_output/graph_prefix.scafSeq.coords.headless > \
>      output/contigs_reports/nucmer_output/graph_prefix.scafSeq.all_snps 2> output/contigs_reports/contigs_report_graph_prefix.scafSeq.stderr
>   1  Alignments: output/contigs_reports/alignments_graph_prefix.scafSeq.tsv
>   1  Analysis is finished

**Comment by alexeigurevich** [comment]
Hi!
You are probably looking into master branch (refactored), not quast-4.1 release (where everything was in contigs_analyzer.py). "headless" creation is here: https://github.com/ablab/quast/blob/master/libs/ca_utils/align_contigs.py#L204 and "alignment_*.tsv" is created here: https://github.com/ablab/quast/blob/master/libs/contigs_analyzer.py#L185 while its content (ref_aligns dictionary) is filled in several units but mostly in https://github.com/ablab/quast/blob/master/libs/ca_utils/analyze_contigs.py (many times).

By the way, you log seems correct and without errors.

**Comment by lamz138138** [comment]
Hi!

I indeed use quast-4.1, thanks for telling me I had looking a wrong file. I tried to spare space to re-run the  pipeline, in case I had omitted some information. It's weird why it was killed. In fact, I had run successfully with another sample.

I would give more information latter, thank you for reply again!

**Comment by lamz138138** [comment]
Hi!

The re-run pipeline was killed again. I had tried to solve it by understanding how nucmer was running, but with little progress since the quast is so powerful with so much codes. Besides, I am use perl and unfamiliar with python make the problem worse. So I think I should look for help again, any suggestion would be grateful!

Following is more informations:

\1. The command:
```
export quastPath="/myPath/quast-4.1"
export scaffPath="/myPath/final.assembly.fasta"
export referencePath="myPath/reference.fa"
$quastPath/quast.py $scaffPath \
        -R $referencePath \
        -o output \
        --threads 40 \
        -s \
        >quast.log 2>quast.err
```

\2. The output log, it said there are 23 threads in parallel, but some information from part were missing (such as lack of part_2), and the line of part_23 was in the same line as previous line:
```
less output/quast.log
Running Contig analyzer...
  1  final.assembly
  1  Logging to files /myPath/output/contigs_reports/contigs_report_final.assembly.stdout and contigs_report_final.assembly.stderr...
  1  Running Nucmer
    Aligning to different chromosomes in parallel (23 threads)
  1  /myPath/quast-4.1/libs/E-MEM-linux/nucmer -c 65 -l 65 --maxmatch \
     -p output/contigs_reports/nucmer_output/final.assembly_part_1.fa -t 1 output/quast_corrected_input/split_ref/part_1.fa \
     output/quast_corrected_input/final.assembly.fasta >> output/contigs_reports/contigs_report_final.assembly.stdout \
     2>> output/contigs_reports/contigs_report_final.assembly.stderr_part1
  1  /myPath/quast-4.1/libs/E-MEM-linux/nucmer -c 65 -l 65 --maxmatch \
     -p output/contigs_reports/nucmer_output/final.assembly_part_3.fa -t 1 output/quast_corrected_input/split_ref/part_3.fa \
     output/quast_corrected_input/final.assembly.fasta >> output/contigs_reports/contigs_report_final.assembly.stdout \
     2>> output/contigs_reports/contigs_report_final.assembly.stderr_part3
  1  /myPath/quast-4.1/libs/E-MEM-linux/nucmer -c 65 -l 65 --maxmatch \
     -p output/contigs_reports/nucmer_output/final.assembly_part_8.fa -t 1 output/quast_corrected_input/split_ref/part_8.fa \
     output/quast_corrected_input/final.assembly.fasta >> output/contigs_reports/contigs_report_final.assembly.stdout \
     2>> output/contigs_reports/contigs_report_final.assembly.stderr_part8
  1  /myPath/quast-4.1/libs/E-MEM-linux/nucmer -c 65 -l 65 --maxmatch \
     -p output/contigs_reports/nucmer_output/final.assembly_part_7.fa -t 1 output/quast_corrected_input/split_ref/part_7.fa \
     output/quast_corrected_input/final.assembly.fasta >> output/contigs_reports/contigs_report_final.assembly.stdout \
     2>> output/contigs_reports/contigs_report_final.assembly.stderr_part7
  1  /myPath/quast-4.1/libs/E-MEM-linux/nucmer -c 65 -l 65 --maxmatch \
     -p output/contigs_reports/nucmer_output/final.assembly_part_11.fa -t 1 output/quast_corrected_input/split_ref/part_11.fa \
     output/quast_corrected_input/final.assembly.fasta >> output/contigs_reports/contigs_report_final.assembly.stdout \
     2>> output/contigs_reports/contigs_report_final.assembly.stderr_part  1  1  /myPath/quast-4.1/libs/E-MEM-linux/nucmer -c 65 -l 65 --maxmatch \
     -p output/contigs_reports/nucmer_output/final.assembly_part_23.fa -t 1 output/quast_corrected_input/split_ref/part_23.fa \
     output/quast_corrected_input/final.assembly.fasta >> output/contigs_reports/contigs_report_final.assembly.stdout \
     2>> output/contigs_reports/contigs_report_final.assembly.stderr_part23
  1  /myPath/quast-4.1/libs/E-MEM-linux/delta-filter -i 95 -l 0 output/contigs_reports/nucmer_output/final.assembly.delta \
     > output/contigs_reports/nucmer_output/final.assembly.fdelta 2> output/contigs_reports/contigs_report_final.assembly.stderr
  1  /myPath/quast-4.1/libs/E-MEM-linux/show-coords output/contigs_reports/nucmer_output/final.assembly.delta \
     > output/contigs_reports/nucmer_output/final.assembly.coords_tmp 2> output/contigs_reports/contigs_report_final.assembly.stderr
  1  /myPath/quast-4.1/libs/E-MEM-linux/show-snps -S -T -H output/contigs_reports/nucmer_output/final.assembly.delta \
     < output/contigs_reports/nucmer_output/final.assembly.coords.headless > output/contigs_reports/nucmer_output/final.assembly.all_snps \
     2> output/contigs_reports/contigs_report_final.assembly.stderr

```

\3. According to the output files in the director of contigs_reports, some files are empty:
```
ls *
-rw-r--r-- 1 lcy01 mobile    0 Jul 16 07:01 all_alignments_final.assembly.tsv
-rw-r--r-- 1 lcy01 mobile    0 Jul 16 07:01 all_alignments_final.assembly.tsv
-rw-r--r-- 1 lcy01 mobile    0 Jul 16 07:01 contigs_report_final.assembly.mis_contigs.info
-rw-r--r-- 1 lcy01 mobile    0 Jul 16 07:01 contigs_report_final.assembly.stderr
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 07:14 contigs_report_final.assembly.stderr_part1
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 07:56 contigs_report_final.assembly.stderr_part10
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 08:05 contigs_report_final.assembly.stderr_part11
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 07:58 contigs_report_final.assembly.stderr_part12
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 07:48 contigs_report_final.assembly.stderr_part13
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 08:04 contigs_report_final.assembly.stderr_part14
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 07:58 contigs_report_final.assembly.stderr_part15
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 08:01 contigs_report_final.assembly.stderr_part16
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 07:57 contigs_report_final.assembly.stderr_part17
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 07:49 contigs_report_final.assembly.stderr_part18
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 07:47 contigs_report_final.assembly.stderr_part19
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 08:21 contigs_report_final.assembly.stderr_part2
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 07:57 contigs_report_final.assembly.stderr_part20
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 07:51 contigs_report_final.assembly.stderr_part21
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 08:02 contigs_report_final.assembly.stderr_part22
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 07:18 contigs_report_final.assembly.stderr_part23
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 08:13 contigs_report_final.assembly.stderr_part3
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 08:13 contigs_report_final.assembly.stderr_part4
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 08:08 contigs_report_final.assembly.stderr_part5
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 08:06 contigs_report_final.assembly.stderr_part6
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 08:05 contigs_report_final.assembly.stderr_part7
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 08:13 contigs_report_final.assembly.stderr_part8
-rw-r--r-- 1 lcy01 mobile  154 Jul 16 07:58 contigs_report_final.assembly.stderr_part9
-rw-r--r-- 1 lcy01 mobile    0 Jul 16 07:01 contigs_report_final.assembly.stdout

nucmer_output:
total 244G
drwxr-xr-x 2 lcy01 mobile 4.0K Jul 19 23:35 .
drwxr-xr-x 3 lcy01 mobile 4.0K Jul 16 07:01 ..
-rw-r--r-- 1 lcy01 mobile 110G Jul 19 23:35 final.assembly.all_snps
-rw-r--r-- 1 lcy01 mobile  28G Jul 19 15:45 final.assembly.coords
-rw-r--r-- 1 lcy01 mobile    0 Jul 19 23:35 final.assembly.coords.filtered
-rw-r--r-- 1 lcy01 mobile  28G Jul 19 15:55 final.assembly.coords.headless
-rw-r--r-- 1 lcy01 mobile  28G Jul 19 15:36 final.assembly.coords_tmp
-rw-r--r-- 1 lcy01 mobile  13G Jul 19 15:13 final.assembly.delta
-rw-r--r-- 1 lcy01 mobile 1.6G Jul 17 20:36 final.assembly_part_10.fa.delta
-rw-r--r-- 1 lcy01 mobile 1.8G Jul 17 22:32 final.assembly_part_11.fa.delta
-rw-r--r-- 1 lcy01 mobile 2.1G Jul 18 07:39 final.assembly_part_12.fa.delta
-rw-r--r-- 1 lcy01 mobile 1.2G Jul 17 11:57 final.assembly_part_13.fa.delta
-rw-r--r-- 1 lcy01 mobile 1.8G Jul 18 00:59 final.assembly_part_14.fa.delta
-rw-r--r-- 1 lcy01 mobile 1.7G Jul 17 23:09 final.assembly_part_15.fa.delta
-rw-r--r-- 1 lcy01 mobile 1.6G Jul 17 20:15 final.assembly_part_16.fa.delta
-rw-r--r-- 1 lcy01 mobile 1.8G Jul 17 23:27 final.assembly_part_17.fa.delta
-rw-r--r-- 1 lcy01 mobile 1.1G Jul 17 09:37 final.assembly_part_18.fa.delta
-rw-r--r-- 1 lcy01 mobile 895M Jul 17 04:23 final.assembly_part_19.fa.delta
-rw-r--r-- 1 lcy01 mobile 3.0K Jul 16 07:15 final.assembly_part_1.fa.delta
-rw-r--r-- 1 lcy01 mobile 1.7G Jul 17 22:02 final.assembly_part_20.fa.delta
-rw-r--r-- 1 lcy01 mobile 1.3G Jul 17 11:13 final.assembly_part_21.fa.delta
-rw-r--r-- 1 lcy01 mobile 2.1G Jul 18 10:01 final.assembly_part_22.fa.delta
-rw-r--r-- 1 lcy01 mobile 6.4M Jul 16 07:27 final.assembly_part_23.fa.delta
-rw-r--r-- 1 lcy01 mobile 3.4G Jul 19 13:38 final.assembly_part_2.fa.delta
-rw-r--r-- 1 lcy01 mobile 2.4G Jul 18 13:11 final.assembly_part_3.fa.delta
-rw-r--r-- 1 lcy01 mobile 2.3G Jul 18 12:06 final.assembly_part_4.fa.delta
-rw-r--r-- 1 lcy01 mobile 2.0G Jul 18 05:33 final.assembly_part_5.fa.delta
-rw-r--r-- 1 lcy01 mobile 2.0G Jul 18 05:41 final.assembly_part_6.fa.delta
-rw-r--r-- 1 lcy01 mobile 2.2G Jul 18 09:16 final.assembly_part_7.fa.delta
-rw-r--r-- 1 lcy01 mobile 2.4G Jul 18 14:24 final.assembly_part_8.fa.delta
-rw-r--r-- 1 lcy01 mobile 1.5G Jul 17 19:58 final.assembly_part_9.fa.delta
-rw-r--r-- 1 lcy01 mobile  126 Jul 19 23:35 final.assembly.sf

```

\4. All information in contigs_report_final.assembly.stderr_part* were same as:

> 1: PREPARING DATA
> 2,3: RUNNING e-mem AND CREATING CLUSTERS
> 4: FINISHING DATA
> 1: PREPARING DATA
> 2,3: RUNNING e-mem AND CREATING CLUSTERS
> 4: FINISHING DATA

\5. The information in final.assembly.sf:

> Assembly file size in bytes: 2648868759
> Reference file size in bytes: 2911858176
> Successfully finished on 2016/07/20 00:19:06

**Comment by alexeigurevich** [comment]
Hi Thanks for the detailed info but I don't see actual error here. Could show how (with which messages) and when Quast crashed? According to final.assembly.sf alignment part was finished successfully, so the problem is probably in post-processing of Nucmer's alignments.

**Comment by lamz138138** [comment]
Hi, I run quest in background ( $quastPath/quast.py ...  &), then use the command "jobs" to trace the job, then I get the status of "killed".

As I mentioned, when I re-run the pipeline with the same command ($quastPath/quast.py ..), it killed again, but with I get more information in quest.log:

```
/myPath/quast-4.1/libs/E-MEM-linux/delta-filter -i 95 -l 0 output/contigs_reports/nucmer_output/graph_prefix.scafSeq.delta \
> output/contigs_reports/nucmer_output/graph_prefix.scafSeq.fdelta 2> output/contigs_reports/contigs_report_graph_prefix.scafSeq.stderr
1 /myPath/quast-4.1/libs/E-MEM-linux/show-coords output/contigs_reports/nucmer_output/graph_prefix.scafSeq.delta \
> output/contigs_reports/nucmer_output/graph_prefix.scafSeq.coords_tmp 2> output/contigs_reports/contigs_report_graph_prefix.scafSeq.stderr
1 /myPath/quast-4.1/libs/E-MEM-linux/show-snps -S -T -H output/contigs_reports/nucmer_output/graph_prefix.scafSeq.delta \
< output/contigs_reports/nucmer_output/graph_prefix.scafSeq.coords.headless > \
output/contigs_reports/nucmer_output/graph_prefix.scafSeq.all_snps 2> output/contigs_reports/contigs_report_graph_prefix.scafSeq.stderr
1 Alignments: output/contigs_reports/alignments_graph_prefix.scafSeq.tsv
1 Analysis is finished
```

Since the file of all_alignments_final.assembly.tsv and inal.assembly.coords.filtered is empty, did you think there are some problem in these steps, or it caused by to huge of the output?

**Comment by lamz138138** [comment]
Hi!

I had found another problem. I think lines in "final.assembly.delta" should be equal to lines in "final.assembly_part_*.fa.delta". However, there are 4,751,621,221 lines in "final.assembly_part_*.fa.delta", while only 900,986,331 lines in "final.assembly.delta". Besides, in the script of "contigs_analyzer.py", there two lines of "chr_delta_file.readline()" in line 278 and 279, is this would be a problem?

**Comment by lamz138138** [comment]
Hi!

This is the latest opinion, I think the problem is caused by lacking of memory. According to line 359 to 375 in "contigs_analyzer.py", it would store nucmer lines in an array, I guess the memory was ran out when storing this information, but I can't find any parameter to skip this steps to test this. Any suggestions?

**Comment by alexeigurevich** [comment]
Hi!
Sorry for the delay, we were extremely busy with release-4.2 but now it is finished and ready for downloading. However, it seems that it will not help much in this situation, I am very sorry for that. See details below:

> I had found another problem. I think lines in "final.assembly.delta" should be equal to lines in "final.assembly_part_*.fa.delta". However, there are 4,751,621,221 lines in "final.assembly_part_*.fa.delta", while only 900,986,331 lines in "final.assembly.delta". Did this result from delta_filter that replace the raw delta file by filtered file ("shutil.move(filtered_delta_fpath, delta_fpath)", line 297)?
Yes, you are right, delta-filter removes unreliable alignments (with IDY% < 95%) and left only the good ones. So, size of "final.assembly.delta" (after shutil.move) should be considerably smaller than total size of all "final.assembly_part_*.fa.delta".

> I think the problem is caused by lacking of memory. According to line 359 to 375 in "contigs_analyzer.py", it would store nucmer lines in an array, I guess the memory was ran out when storing this information, but I can't find any parameter to skip this steps to test this. Any suggestions?
Yes, I am almost sure the problem is here. We need to load everything to memory and in your case it is ~28 Gb (it should be less because we store not everything but it is still a huge amount of memory). QUAST was initially designed for bacterial genomes, later we extend it to genomes of ~500Mb size but it was never well tested on human-size genomes yet. Actually we did some tests but they were performed on powerful servers with >100 GB RAM. 
We plan to start working on the version for large genomes really soon. It will include more effective (both memory and accuracy) processing of alignments. However, this work will take a while, so it is difficult to estimate how long it may take. 
Unfortunately, there is no quick workaround in your case. I can only suggest to set more strict filtration in delta-filter step (line 288), lets say 100 or 99 instead of 95. Thus, only the very best alignments will remain and the memory consumption should decrease (hopefully significantly). The other side of the coin is that you can miss some important alignments with IDY between 95 and your new threshold. Also you could use --no-snps option which will also decrease memory consumption on further steps. In both cases you may use the same directory as an output and Quast will reuse all already generated alignment files without rerunning Nucmer again.

I hope my answer will be useful!
