### ISSUE TITLE
MetaQUAST: add average read support of reference (based on contigs)

### ISSUE THREAD

**Issue by vladsaveliev** [ablab/quast#22]
Request from Dmitry Antipov:

At least for MetaSPAdes, we can extract average read support from contig names (i.e. NODE_1_length_1833779_cov_52.589). Add metric in reference-based reports "Ave contig read support". Calculate it based on coverages of contigs that have a large enough alignment to this reference (>90%?)

**Comment by alexeigurevich** [comment]
Metric (named "Avg contig read support") added but only if --read-support option is specified. Currently this option is in "hidden" section, so mostly intended for internal use. Probably we will add something more "honest" (based on reads alignment) in next major release.
