### ISSUE TITLE
quast output 

### ISSUE THREAD

**Issue by MelakG13** [ablab/quast#224]
I have tried to do quast, but i found this error repeatedly. Please can any one tell me how could I resolve this.

melak@user:/mnt/c/Users/melak/ABySS Assignment$ quast.py -o quast_report ecoli-scaffolds.fa
ERROR! QUAST does not support spaces in paths.
You have specified /mnt/c/Users/melak/ABySS Assignment/quast_report as an output path.
Please, use a different directory.

**Comment by alexeigurevich** [comment]
Hi,
As the error message explains, QUAST doesn't support spaces (and a few other special characters) in path to files and directories. You are running it from `/mnt/c/Users/melak/ABySS Assignment` that has a space between "ABySS" and "Assignment", so both paths to `quast_report` and `ecoli-scaffolds.fa` also include this space character.

Please rename your directory without spaces, e.g.,
`mv /mnt/c/Users/melak/ABySS Assignment /mnt/c/Users/melak/ABySS_Assignment`
and try again.
