### ISSUE TITLE
ERROR! Skipping ...fasta.gz because >sequence_name field is empty

### ISSUE THREAD

**Issue by I-Jenn** [ablab/quast#231]
Hello,

Excused me. I've been trying to run reference-based assembly, though some error showed up that I couldn't find a way to fix it. The [quast.log](https://github.com/ablab/quast/files/10276703/quast.log) is attached. And there's my command below:
command 1.
```
quast.py
   ../20241HHL_Ca0437g_S12_L002_R1_001.fastq.gz
   ../20241HHL_Ca0437g_S12_L002_R2_001.fastq.gz
   -r ../KpCa0437g-sync4.fna
```
command 2.
```
quast.py 
   -r ../KpCa0437g-sync4.fna 
   -1 ../20241HHL_Ca0437g_S12_L002_R1_001.fastq.gz 
   -2 ../20241HHL_Ca0437g_S12_L002_R2_001.fastq.gz
```
I followed the [manual](https://quast.sourceforge.net/docs/manual.html) and [the other issue](https://github.com/ablab/quast/issues/72) written before, though the problem didn't solved, thinking I could get some help there.

Thanks for your attention.
Regards,
Ijenn

**Comment by alexeigurevich** [comment]
Hi Ijenn, 

You probably confused QUAST and SPAdes (https://github.com/ablab/spades) projects. SPAdes is a genome assembler (though, it is not reference-based) and QUAST is a tool for the evaluation of genome assembly quality. So, QUAST will not generate assemblies itself, on contrary, it requires at least one assembly as input. QUAST can accept reads in FASTQ (via `-1` and `-2`) as auxiliary input data and uses them mainly for reporting the number and quality of read alignments to evaluated assemblies.

**Comment by I-Jenn** [comment]
Thank you very much for the explanation! I see it now.
