### ISSUE TITLE
Large genomes

### ISSUE THREAD

**Issue by sjackman** [ablab/quast#26]
QUAST previously was not recommended for large (mammalian) genomes. Is that still the case for QUAST 4.3?

**Comment by alexeigurevich** [comment]
Hi Shaun,
Yes it is still the case in general. We plan to significantly improve support for large genomes since QUAST 5.0. However, we made few fixes in upcoming 4.4 and also I wrote a special section in our manual about recommended options in this case (see FAQ, Q14).

**Comment by sjackman** [comment]
Okay. Thanks for the FAQ. The question says "but my computational resources are limited". I have lots of computational resources, 64 threads and 2 TB of RAM. In that case shall I use the default parameters?

**Comment by alexeigurevich** [comment]
Yes if you have enough resources than feel free to use default settings. These suggestions are for case when something crashed (because of not enough RAM, hard disk or just very slow processing). So, you should check this FAQ section if something is going wrong :)

**Comment by sjackman** [comment]
E-MEM has been running for three days. Any estimate of how long it takes to align a human assembly to the reference?

**Comment by alexeigurevich** [comment]
Well, we do not have such benchmarks. As I know, E-MEM authors added their aligner to Quast 2.3, called this tool LASER and made some benchmarks on human assemblies here: http://www.csd.uwo.ca/~ilie/LASER/  Unfortunately there is no information about number of threads or test computer performance.
Note that we contacted with them at some point and included E-MEM into Quast v4, so there is no separate LASER tool anymore.
From my point of view, 3 days should be enough. Do you have one assembly or several?

**Comment by sjackman** [comment]
It's still running four days later. 7 processes of `postnuc` are running at 100%. The `nucmer_output` folder is at 104 GB.

**Comment by sjackman** [comment]
The LASER benchmarks say that QUAST takes ~4 days and LASER takes ~1 day for a human assembly. http://www.csd.uwo.ca/~ilie/LASER/

I have eight human genome assemblies to analyze.

**Comment by asl** [comment]
I would not trust LASER benchmarks :)

**Comment by sjackman** [comment]
What's the current status of QUAST on a mammalian-sized genome?

**Comment by asl** [comment]
Hi @sjackman 

This is currently WIP, but you can give http://cab.spbu.ru/software/quast-lg/ a try

**Comment by sjackman** [comment]
Thanks, Anton!

**Comment by sjackman** [comment]
KMC is using 240 GB of disk space for a human assembly. It's also using 0% CPU and seems to be stalled out. Is there an option to skip the KMC analysis?
```
   PID USER      PR  NI    VIRT    RES  %CPU %MEM     TIME+ S COMMAND          
 50553 sjackman  20   0 16.232g 0.014t   0.0  0.6  10:55.93 S kmc              
```

**Comment by alexeigurevich** [comment]
Hi, Shaun!
Thanks for the bug report! We have tested KMC with human assemblies at some point but made some changes in this module after that. Maybe this changes caused the troubles. We will try to deeply investigate this issue asap. 
Anyway, your suggestion about option for disabling KMC totally make sense since it is new additional functionality and not all QUAST users actually need it. We plan to submit a fix for this today which will make KMC disabled by default and add `--kmc` option for enabling it by request. Stay tuned!

**Comment by alexeigurevich** [comment]
Shaun, you may take a try, thanks to @almiheenko

**Comment by sjackman** [comment]
I'm doing so now. Thanks!

**Comment by sjackman** [comment]
It works! Thanks for your quick responses, Alex!

**Comment by alexeigurevich** [comment]
I hope we can close this issue now :)

**Comment by sjackman** [comment]
❤️ 🎉 🍾 🎈 🎆
