### ISSUE TITLE
Issues running quast.

### ISSUE THREAD

**Issue by SoSongzhi** [ablab/quast#265]
Hello there,

I have a problem using Quast.

"ERROR! Compilation of contig aligner software was unsuccessful! QUAST functionality will be limited.
Failed aligning the contigs for all the assemblies. Only basic stats are going to be evaluated."

Can anyone help me out please?

Thank you.

**Comment by alexeigurevich** [comment]
Hi, 
This usually means the minimap2 aligner provided within the Quast package failed to compile for some reason. You might try to install it independently, e.g., via [conda](https://anaconda.org/bioconda/minimap2). If `minimap2` is present in the system (in the PATH environment variable), Quast will reuse it without compiling the embedded version and this Error should disappear. Note that Quast relies a lot on this aligner (if you plan to run the tool with a reference genome), so without it, the functionality is severely limited
