### ISSUE TITLE
GeneMark license?

### ISSUE THREAD

**Issue by csmatyi** [ablab/quast#271]
Hi,
I wanted to download a GeneMark license from https://exon.gatech.edu/GeneMark/license_download.cgi
But, when I select the appropriate software and operating system, it takes me to this page:

--------------

GeneMark* software
If you are an academic, non-profit institution or U.S. Governmental agency, you may use these Products royalty free. All other interested parties should use [this link](https://exon.gatech.edu/GeneMark/contact.html).

Download instructions

----------

No download instructions. What should I do?
Thanks, Matthew

**Comment by asl** [comment]
> No download instructions. What should I do?

You'd better ask GeneMark. This is what shows for me right now:

<img width="1146" alt="Screenshot 2024-08-14 at 10 25 31" src="https://github.com/user-attachments/assets/fdac111c-b995-41c3-8976-8fad9ea72d6d">

**Comment by asl** [comment]
As far as I can see, there is contact information at https://exon.gatech.edu/GeneMark/contact.html:

Theory and algorithms questions:
Mark Borodovsky
[borodovsky@gatech.edu](mailto:borodovsky@gatech.edu)

Website or local software questions/problems, local software license (please indicate your institution/company):
Alex Lomsadze
[alexl@gatech.edu](mailto:alexl@gatech.edu)

**Comment by csmatyi** [comment]
okay I wrote to both of them but am waiting for their response. This is
important for me because I just finished the sand cat genome and would like
to annotate it with GeneMark.
Thanks, Matt

**Comment by asl** [comment]
Note that QUAST is neither affiliated nor connected with GeneMark, so QUAST team cannot help more than already available on their website

**Comment by csmatyi** [comment]
Thank you for the clarification.
