### ISSUE TITLE
minor bug or verbose issue: --min-contig and checks

### ISSUE THREAD

**Issue by jfouret** [ablab/quast#273]
Hi, 

With default `--min-contig` value (500) I got this error: 

```
ERROR! Number of chromosomes in /home/jfouret/Documents/github/nexomis/viral-assembly/work/75/1d032b5ce6668a6180f26c036f888a/s1/quast_corrected_input/s1_spades_r
naviral.fa and corresponding file inputs/aln01.bam do not match. Use SAM file obtained by aligning reads to /home/jfouret/Documents/github/nexomis/viral-assembly
/work/75/1d032b5ce6668a6180f26c036f888a/s1/quast_corrected_input/s1_spades_rnaviral.fa
```

When I set the `--min-contig 0`, I got no errors.
I suspect that this checks the names after filtering whereas alignment can be performed before.

However since it makes no sense to map on contigs that we do not consider after, throwing an error can be justified, or a waring maybe.

Bests and thank you for this tool.

**Comment by alexeigurevich** [comment]
The better error message solution was implemented and released in v.5.3.0. Thanks!
