### ISSUE TITLE
Unable to create a  summarized html report from different contig files.

### ISSUE THREAD

**Issue by Uzocodex** [ablab/quast#274]
Hello,

Please I need some help. I would like to have a summarized html report that shows all contigs in one html report file, instead of individual html reports for each contig. I had assembled the contigs using MEGAHIT, Thank you.

**Comment by alexeigurevich** [comment]
Hello, 
Just specify the paths to all your assemblies in one Quast running command and the reports will be combined into one automatically, e.g.:
`quast.py -o report  assembly_1.fna assembly_2.fna assembly_3.fna`  (feel free to add other options, e.g., specify a reference genome with `-r` if applicable)

**Comment by Uzocodex** [comment]
Thank you for your treasured response. However I think I already did. Perhaps review my code and see whether I was wrong...

contigs_dir=/home/uzobiocodes/HP_genome_analysis/megahit_result

#Find all .fa files in the directory, and return array of .fa with absolute path
finalcontigs=$contigs_dir/*.fa    
#echo $finalcontigs  #{finalcontigs[@]}

#Path to reference genome and genes
reference=/home/uzobiocodes/HP_genome_analysis/Mapping/Indexed_reference_genome/GCF_000307795.1_ASM30779v1_genomic.fna
genes=/home/uzobiocodes/HP_genome_analysis/Mapping/Indexed_reference_genome/genomic.gff

mkdir -p megahitquast_result

#Run in the  folder containing the files<
for file in $finalcontigs;        do

   # Extract the base filename without the extension
  base_filename=$(basename "$file" .fa)

  # Create a unique output directory for this FASTA file
  output_subdir="megahitquast_result/$base_filename"
  mkdir -p "$output_subdir"
  
    n=$(basename ${file%%/.fa})
     
  quast.py -t 4 -o $output_subdir -r $reference -g $genes $file 

	done
done

**Comment by Uzocodex** [comment]
Also When I don´t separate the different files in their respective folders, I get a summary report of only one of the contig files. Using the code below;

contigs_dir=/home/uzobiocodes/HP_genome_analysis/megahit_contigs

#Path to reference genome and genes
reference=/home/uzobiocodes/HP_genome_analysis/Mapping/Indexed_reference_genome/GCF_000307795.1_ASM30779v1_genomic.fna
genes=/home/uzobiocodes/HP_genome_analysis/Mapping/Indexed_reference_genome/genomic.gff

mkdir -p megahitquast1_result

#Run in the folder containing the contig files
for file in $contigs_dir/*.fa; do

quast.py -t 4 -o megahitquast1_result -r $reference -g $genes $file

done

**Comment by alexeigurevich** [comment]
Hi, you are currently running separate "quast.py" commands for every assembly (.fa file) in your loop. For the single report, replace the for loop with just a single command (`*.fa` will automatically expand to all files with the .fa extension and they all will be analyzed together by Quast and result in a single summary report):

```
quast.py -t 4 -o megahitquast1_result -r $reference -g $genes $contigs_dir/*.fa
```

**Comment by Uzocodex** [comment]
Thank you so much Alexy, it took me more than 10 months to figure it out.
It really worked.I am very grateful for your help.
