### ISSUE TITLE
Incorrect path

### ISSUE THREAD

**Issue by ad3002** [ablab/quast#3]
I got:

"The tool returned non-zero. See ../../../../../../../storage1/akomissarov/pacbio/quast_results/results_2015_07_01_14_10_36/busco_output/busco.err for stderr."

and it should be:

"The tool returned non-zero. See /storage1/akomissarov/pacbio/quast_results/results_2015_07_01_14_10_36/busco_output/busco.err for stderr."

Probably you should check if it is an absolute path or not with

```
 if not os.path.isabs(path):
```

**Comment by alexeigurevich** [comment]
Busco was removed from the master branch, so closing this issue
