### ISSUE TITLE
Metaquast silva and ncbi database matching

### ISSUE THREAD

**Issue by kevlim83** [ablab/quast#30]
Hi,

I am using metaquast to evaluate my metagenomics data. As I understand, metaquast will search for the top most matching 16S rRNA from SILVA and then try to download the complete genomes from NCBI. However, I noticed many entries in SILVA cannot be found on NCBI, thus limiting the analysis. Have you guys thought of ways to overcome this problem? E.g. One naive way is to look for the next best SILVA 16S rRNA if the current one does not have a matched NCBI entry.

What do you think?

Regards,
K

**Comment by alexeigurevich** [comment]
Thanks for the suggestion! This was implemented in v5.0.0
