### ISSUE TITLE
misassembled contig

### ISSUE THREAD

**Issue by efratca** [ablab/quast#33]
Hi,

I ran quast on E.coli assembly (1 contig) and I got in the contig size viewer a misassembled contig and also in the contig alignment viewer almost all the contig was misassembled.
The following is the mummerplot: 
![image](https://user-images.githubusercontent.com/30207940/29248100-b8ceddec-8017-11e7-8697-a4e816aff408.png)
Is the contig misassembled because the genome is circular? Is there a way to change the criterions for misasembly to get a correct contig?

Thanks

**Comment by alexeigurevich** [comment]
Hi!
By default, Quast correctly processes circular genomes (does not report a misassembly), so this should not be a problem. Note: you can disable this behaviour with --eukaryote option.
However, it looks like there are a lot of small discrepancies with the reference genome (it could be imperfect reference or natural diversity of the sequenced organism, e.g. structural variations). We usually call them local misassemblies. They are shown as errors (red) on Icarus contig alignment viewer by default, but you could simply hide them using top control panel:
![image](https://user-images.githubusercontent.com/620893/29276579-b2ffd938-8117-11e7-8873-dd9cc905eeff.png)
After this, you can focus on other types of misassemblies which are more severe and may correspond to true assembly errors. As far as I can see from the mummer plot, probably all your errors are local misassemblies, so do not worry about them much.
Note that you can control the threshold distinguishing local and extensive misassemblies with --extensive-mis-size option (or simply -x). The default value is 1000 bp long inconsistency. 

Best,
Alexey

**Comment by efratca** [comment]
Thanks a lot for the reply
