### ISSUE TITLE
No handlers could be found for logger "quast"

### ISSUE THREAD

**Issue by abayega** [ablab/quast#36]
Dear,

kindly assist me to determine what is going wrong. I just unzipped quast and run
./install_full.sh
which returned
 
Starting QUAST test... (stdout redirected to ./install_log.stdout)
No handlers could be found for logger "quast"
ERROR! QUAST TEST FAILED!

It seems compilation of Mummer fails with (make: *** No targets specified and no makefile found.  Stop.)

Install log is attached.

 
I have loaded the following modules
 
jdk64
gcc/4.8.2
perl5/5.18.2
python64/3.5.2
 
Thanks
Anthony

**Comment by alexeigurevich** [comment]
Hi Anthony,

It looks like you forgot to attached the log! 
By the way, "No handlers could be found for logger "quast"" is just a warning (we will fix it anyway). The real problem is in Mummer compilation, probably I will have some hints about it when I take a look at the log.

**Comment by abayega** [comment]
Hi,
sorry, now attached
[install_log.stdout.txt](https://github.com/ablab/quast/files/1252632/install_log.stdout.txt)

**Comment by alexeigurevich** [comment]
Hi,
The problem is indeed in Mummer compilation. Could you also attach /netmount/ip14_home/banthony/software/quast-master/quast_libs/MUMmer/make.log and make.err (this one is the most important).

**Comment by abayega** [comment]
Hi, attached.

Also, is there a reference genome size limitation in Mummer?

[make.err.txt](https://github.com/ablab/quast/files/1257195/make.err.txt)
[make.log.txt](https://github.com/ablab/quast/files/1257194/make.log.txt)

**Comment by alexeigurevich** [comment]
Hi Anthony,

Could you try ./install.sh again with the latest version from the master branch. If you see "ERROR! QUAST TEST FAILED!" again please attach the same log files -- we've just added more debug information to them.
Also note that stable Quast releases are distributed from https://sourceforge.net/projects/quast/files/ (or releases tab at github.com). Using our constantly changing master branch is a little bit risky and error prone :)
And one more note: you can always write to quast.support@cab.spbu.ru if you want a private conversation/data sharing.

**Comment by abayega** [comment]
Hi, these are attached,
thanks
[config.log.txt](https://github.com/ablab/quast/files/1264006/config.log.txt)
[install_log.stdout.txt](https://github.com/ablab/quast/files/1264008/install_log.stdout.txt)
[make.err.txt](https://github.com/ablab/quast/files/1264007/make.err.txt)

[make.log.txt](https://github.com/ablab/quast/files/1264005/make.log.txt)

**Comment by alexeigurevich** [comment]
Hi Anthony,

Sorry for the delay. It looks like the main problem is reported in config.log.txt:
`/usr/bin/ld: cannot find -lc`
Which means that linker cannot find the C libraries for static compilation. See similar problem here: https://stackoverflow.com/questions/16024978/usr-bin-ld-cannot-find-lc-while-compiling-with-makefile
So you probably need to load these libraries to your system.

**Comment by abayega** [comment]
How can I provide quast with the PATH to the precompiled mummer executables since I have these already?

**Comment by abayega** [comment]
Hi, you can mark this issue as solved. I was able to download quast-4.5 from sourceforge which compiled Mummer well except for E-MEM, which requires boost/algorithm/string.hpp that I cannot find on the system. 

Thanks

**Comment by alexeigurevich** [comment]
Hi,
Yes, previous Mummer (3.23 used in Quast versions 1.0 - 4.5) was more friendly for compilation (except optional E-MEM module added in v.4).
However, we plan to switch to new Mummer (4.0-beta) in the next release, so we added it in the master branch and that caused problems e.g. on your particular system. So, we will work on further improvement of new Mummer adaptation to make it work everywhere.

**Comment by alexeigurevich** [comment]
Closing the old issue -- note that we finally switched to minimap2 aligner in the master branch and upcoming Quast v5.0
