### ISSUE TITLE
python 3 compat in 

### ISSUE THREAD

**Issue by cokelaer** [ablab/quast#39]
FYI there are quite a few python3 incompatible statements in quast_libs/site_packages/joblib

**Comment by alexeigurevich** [comment]
Hi!
Sorry for a huge delay. Actually we have quast_libs/site_packages/joblib for Python 2.* and quast_libs/site_packages/joblib3 for Python 3.* and thus something in joblib is not compatible with Python3 and vice versa.  We will rename joblib -> joblib2 to exclude the confusion.
