### ISSUE TITLE
Misaligned scaffold

### ISSUE THREAD

**Issue by sjackman** [ablab/quast#49]
Just a heads up that this issue https://github.com/lh3/minimap2/issues/104 caused QUAST to incorrectly report a misassembly, fixed now in minimap2 r677. You'll want to update minimap2 2.9 when it's released.

**Comment by alexeigurevich** [comment]
Thanks for noticing, will wait for v2.9!

**Comment by alexeigurevich** [comment]
Forgot to close the issue but we are even on minimap2 v2.10-r761 now (an keep updating it)
