### ISSUE TITLE
metaquast with option --max-ref-number

### ISSUE THREAD

**Issue by RootQJZ** [ablab/quast#52]
Hi,

When I run metaquast without references and with option --max-ref-number 200 to find references in SILVA database, it only gave 48 organisms (tried to download) after blastn running. Dose this mean my contigs only match 48 organisms in SILVA database? I was trying to find more references for the analysis. Any ideas?

Here is the metaquast log file:
[metaquast.log](https://github.com/ablab/quast/files/1699813/metaquast.log)

Thanks!

**Comment by alexeigurevich** [comment]
Hi!
Sorry for the delay. Could you please try our new version from the master branch. We've made several fixes which may affect this feature as well, so this time you may find more than 48 references. Please let us know how it is going!
