### ISSUE TITLE
minimap2 "-asm10" option

### ISSUE THREAD

**Issue by davidvilanova** [ablab/quast#53]
Hi,
I have assembled nanopore reads and i expect the identity between my assembly and the reference around 92%. Latest dev of quast implements the ` -asm5` option for minimap2 and  i get a genome fraction around 45% between my assembly and the reference bacterial genome.

Since i expect my assembly to be less than 95% aligned to the reference is it possible to have the `-asm10` option implemented ???

**Comment by alexeigurevich** [comment]
Hi David,
Nice to see that your problem was solved! Could you please briefly describe why you closed the issue -- for future users who may potential face the same problem and find this issue.
