### ISSUE TITLE
how to combine the results of different assembly using quest

### ISSUE THREAD

**Issue by U201412486** [ablab/quast#54]
Hi,
  I want to combine these in a figure to compare  after I got several   "report.pdf"  with assembly results of different assembly tools. Just like the figure as "http://bioinf.spbau.ru/quast" shows. What should I do? Any Ideas?

Thanks!

**Comment by U201412486** [comment]
I am sorry to write error "quest" in the title. It should be "quast".

**Comment by alexeigurevich** [comment]
Hi,
You cannot combine ready PDF file. Instead, just specify all your assemblies in a single Quast run and it will create a single report.pdf (and all other reports, e.g. report.html) with all assemblies.
E.g.,
`./quast.py -R reference.fa  assembly1.fa assembly2.fa assembly3.fa -o my_output_dir`

**Comment by U201412486** [comment]
Thank you very much! It works.
