### ISSUE TITLE
Using mummer4 instead of E-MEM

### ISSUE THREAD

**Issue by songtaogui** [ablab/quast#56]
Hi there,

How could I using nucmer in mummer4 to align contigs rather than E-MEM embeded in quast?  
Since Quast can use existing alignment files to do the evaluation, could I run nucmer stand alone and copy the output into "/contigs_reports/nucmer_output/", and which files are needed to skip the alignment step in Quast?

Thanks!

**Comment by alexeigurevich** [comment]
Hi!
I am very sorry about the huge delay in answering this. We indeed can use existing alignment files, however, we do some tricky checks to prevent reuse of incorrect alignments (e.g. generated using similar but not equivalent reference or assembly). So, using MUMmer4 is technically possible but it is rather difficult and requires ad-hoc scripting or modifying Quast source code.

Note that we've recently released Quast v.5.0 with very fast minimap2 aligner inside. It replaced our previous default mummer3 and E-MEM aligners and it is _significantly_ faster than those two. During our long v.5.0 release preparation we also tried to incorporate mummer4 in the tool but our benchmarks showed that minimap2 is even faster than the improved mummer. So, I hope you don't need to use mummer4 with Quast anymore and will simply switch the fast Quast v.5!
