### ISSUE TITLE
how to keep the nucmer delta file 

### ISSUE THREAD

**Issue by songtaogui** [ablab/quast#57]
Hi,

I would like to use the ".delta" file generated by  nucmer to do further analysis. It seems that quast remove the "delta" file automaticly. So how could I keep the "delta" file?

Thanks a lot!

**Comment by alexeigurevich** [comment]
Hi,
You can run Quast with `--debug` option and delta files will be preserved (under `<quast_output_dir>/contigs_reports/nucmer_output/`). 

Note: if you have run Quast without `--debug` and rerun it with `--debug` with the same output folder, Quast will reuse existing alignments and thus do not run Nucmer, i.e. do not create the delta file. So, to get the delta file you should run Quast with `--debug` from scratch (using a clean output directory).

**Comment by songtaogui** [comment]
Thanks!
