### ISSUE TITLE
Error when running quast

### ISSUE THREAD

**Issue by U201412486** [ablab/quast#59]
Hello,
I'm getting the following error when trying to run quast w/ even the most simple parameters (quast.log):
/home/niuyw/software/quast-4.6.3/quast.py /home/niuyw/Project/beetle_genome_171231/data/third/17
0111.fasta /home/niuyw/Project/beetle_genome_171231/data/third/171224.fasta /home/niuyw/Project/
beetle_genome_171231/data/third/third_all.fasta -m 0 -l 170111,171224,all -o third_quast --no-ch
eck -t 10 --no-icarus --no-html --no-plots

Version: 4.6.3

System information:
  OS: Linux-2.6.32-504.el6.x86_64-x86_64-with-centos-6.6-Final (linux_64)
  Python version: 2.7.13
  CPUs number: 12

Started: 2018-05-03 10:40:23

Logging to /home/niuyw/sxh/quast/data/third_quast/quast.log
NOTICE: Output directory already exists. Existing Nucmer alignments can be used

CWD: /home/niuyw/sxh/quast/data
Main parameters: 
  Threads: 10, ambiguity: one, threshold for extensive misassembly size: 1000

Contigs:
  Pre-processing...

Traceback (most recent call last):
  File "/home/niuyw/software/quast-4.6.3/quast.py", line 281, in <module>
    return_code = main(sys.argv[1:])
  File "/home/niuyw/software/quast-4.6.3/quast.py", line 93, in main
    contigs_fpaths, old_contigs_fpaths = qutils.correct_contigs(contigs_fpaths, corrected_dirpat
h, labels, reporting)
  File "/home/niuyw/software/quast-4.6.3/quast_libs/qutils.py", line 206, in correct_contigs
    corrected_dirpath, labels) for i, contigs_fpath in enumerate(contigs_fpaths))
  File "/home/niuyw/software/Python.2.7.13/lib/python2.7/site-packages/joblib-0.11-py2.7.egg/job
lib/parallel.py", line 789, in __call__
    self.retrieve()
  File "/home/niuyw/software/Python.2.7.13/lib/python2.7/site-packages/joblib-0.11-py2.7.egg/job
lib/parallel.py", line 699, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/niuyw/software/Python.2.7.13/lib/python2.7/multiprocessing/pool.py", line 567, in 
get
    raise self._value
MemoryError

Any help would be greatly appreciated.

**Comment by alexeigurevich** [comment]
Hello, it looks like there is not enough memory (RAM) on your machine (see `MemoryError ` in the log).
Please try to rerun with `-t 1` or even with `--memory-efficient` (will be slow).

**Comment by U201412486** [comment]
Thank you for your advice.Maybe there is not enough memory (RAM) on my machine,it does not work trying  rerunning with -t 1 or even with - --memory-efficient.

**Comment by alexeigurevich** [comment]
Yes, unfortunately,  it looks like the limited RAM causing the issue in this case. 
Note: we are working on optimizing our software but for large genomes, it still requires pretty much RAM. This may change in some future releases.
