### ISSUE TITLE
About unaligned mis. contigs

### ISSUE THREAD

**Issue by taoistly** [ablab/quast#61]
Hi,

I read the Q15 at QUAST manual(http://quast.bioinf.spbau.ru/manual.html#faq_q15) which really explains what happened to my evaluation. I tried to compare a scaffold-level assembly A with its broken version B. 

In the report, A has more misassemblies and less unaligned mis. contigs.  So I checked the alignment details and identified a case:  A merges 2 contigs in B. One of them is unaligned mis. contigs and thus misassemblies on this contig are not counted in B. But in A, this contig is merged with a perfectly aligned contig so that all misassemblies in this contig counts.

I think this make comparison unfair. The real misassemblies number is diluted and even overwhelmed by identity change of unaligned mis. contigs. May I ask for a option to include unaligned mis. contigs in misassembly counting? In other words, the misassemblies in all contigs should counts without exempt.

Thank you.

**Comment by taoistly** [comment]
This behavior looks controlled by `umt` at `quast_libs/ca_utils/analyze_contigs.py: line 98`.
I think an option to customize `umt` (as 0 or other value) would work.

**Comment by alexeigurevich** [comment]
Hi,
Thank you for the great suggestion, we will add such option asap. 
You are absolutely right about `umt` -- this is the only parameter that control the thing. Currently, you may hard code it to 0 if you want.

**Comment by alexeigurevich** [comment]
You can use `--skip-unaligned-mis-contigs` option now (in the master branch and hopefully in v.5.0. soon). The option sets `umt = 0` (default value is still 0.5).
Thanks for the suggestion!

**Comment by taoistly** [comment]
That's great. Thank you so much!
