### ISSUE TITLE
Failed loading BUSCO database

### ISSUE THREAD

**Issue by alexandervogel** [ablab/quast#65]
Hi, I tried to run quast-5.0.0 on a sample and in test mode with the following command:

`./quast.py --conserved-genes-finding --test`

and got an error message about a failed download of the corresponding database.

`
ERROR! Failed downloading bacteria database (url: https://busco.ezlab.org/v2/datasets/bacteria_odb9.tar.gz), QUAST functionality will be limited! Exception caught: ('http error', 301, 'Moved Permanently', <httplib.HTTPMessage instance at 0x7fa3e91185a8>)
`

I can wget the database from the same url without any issues. Is there a way to pre-install the required database?

**Comment by alexeigurevich** [comment]
Hi, 
It looks like an issue on the busco side, sometimes this links works correctly and sometimes it returns "Moved Permanently". We will try to find a workaround for it.

However, yes -- you can pre-install the database by your own. It is pretty easy -- see below.

QUAST downloads third-party tools and databases in one of two possible locations: either under `<quast_installation_dir>/quast_libs/` (by default) or under `~/.quast/` (if there are no writing permissions for the default location, e.g. you've installed quast via pip and it was located under `/usr/local/lib/python3.6/dist-packages/quast_libs/`).
The relative locations for BUSCO databases are `./busco/<clade>` where `<clade>` is `bacteria` (your case), `fungi`, or `eukaryota`. 

So, all you need is to 
1. create directory `<quast_installation_dir>/quast_libs/busco/bacteria/` or `~/.quast/busco/bacteria/` (which one you prefer).
2. download the database (`bacteria_odb9.tar.gz`)
3. unpack the archive and place its content (e.g. files `dataset.cfg`, ` hmms`, etc) under `<quast_installation_dir>/quast_libs/busco/bacteria/` or `~/.quast/busco/bacteria/`

Next time you run Quast with `--conserved-genes-finding` (or simply `-b`), it should be able to detect the DB and use it properly. Let me know if something is unclear or not working!

**Comment by lparsons** [comment]
I'm running into this issue again. This appears to be a fairly old version of BUSCO (v2) as they are now up to v4. Perhaps they no longer provide these databases?

**Comment by ptrebert** [comment]
Same for me here... Also, it would be nice if `quast-download-busco` would return a non-zero exit code if any of the databases fail to download

**Comment by pdimens** [comment]
I am having the same issue, and after following the instructions to manually add it above, I'm still getting the same error:
```
2020-10-06 12:25:21
Running BUSCO...
  Downloading BUSCO database...
Downloading eukaryota database (file: eukaryota.tar.gz)...

ERROR! Failed downloading eukaryota database (url: https://busco.ezlab.org/v2/datasets/eukaryota_odb9.tar.gz), QUAST functionality will be limited! Exception caught: ('http error', 301, 'Moved Permanently', <httplib.HTTPMessage instance at 0x7f56e6945dd0>)
You can try to download the file manually, place it in /mnt/secondary/pdimens/yft_genome_v2/Talbacares_02/software/quast/quast_libs/busco/eukaryota.tar.gz and restart QUAST
WARNING: Failed to download eukaryota database from https://busco.ezlab.org/v2/datasets/eukaryota_odb9.tar.gz and unpack it into /mnt/secondary/pdimens/yft_genome_v2/Talbacares_02/software/quast/quast_libs/busco
Failed finding conservative genes.
```
And my directory structure looks like:
```
# quast/quast_libs/busco/
├── BuscoAnalysis.py
├── BuscoConfig.py
├── BuscoConfig.pyc
├── busco.py
├── busco.pyc
├── config.ini.default
├── eukaryota_odb9.tar.gz
├── eurkaryota
│   ├── ancestral
│   ├── ancestral_variants
│   ├── dataset.cfg
│   ├── eukaryota_odb9
│   ├── hmms
│   ├── info
│   ├── lengths_cutoff
│   ├── prfl
│   └── scores_cutoff
├── GeneSetAnalysis.py
├── GenomeAnalysis.py
├── hmmsearch
├── info
│   ├── ogs.id.info
│   └── species.info
├── __init__.py
├── __init__.pyc
├── pipebricks
│   ├── __init__.py
│   ├── __init__.pyc
│   ├── PipeConfig.py
│   ├── PipeConfig.pyc
│   ├── PipeHelper.py
│   ├── PipeLogger.py
│   ├── PipeLogger.pyc
│   ├── __pycache__
│   └── Toolset.py
├── prfl [303 entries exceeds filelimit, not opening dir]
├── __pycache__
│   ├── BuscoConfig.cpython-36.pyc
│   ├── busco.cpython-36.pyc
│   ├── __init__.cpython-36.pyc
│   └── _version.cpython-36.pyc
├── TranscriptomeAnalysis.py
├── _version.py
└── _version.pyc
```

**Comment by PHemarajata** [comment]
Same issue.
