### ISSUE TITLE
specify multiple input library

### ISSUE THREAD

**Issue by mossishahi** [ablab/quast#66]
how should multiple input libraries be specified? 
I read your documentation, a part is mentioned below, and I didn't understand how to specify multiple libraries as inputs of Quast-LG.
we have 3 libraries of each type of mate-pair and paired-end (9 libs. or 18 files aggregated. )and tend to use Quast-LG for getting some analyzes and also upper bound assembly.
> --pe1 (or -1) <path>
> File with forward paired-end reads in FASTQ format (files compressed with gzip are allowed).
> --pe2 (or -2) <path>
> File with reverse paired-end reads in FASTQ format (files compressed with gzip are allowed).
> --pe12 (or --12) <path>
> File with interlaced forward and reverse paired-end reads in FASTQ format (files compressed with gzip are allowed).
> --mp1 <path>
> File with forward mate-pair reads in FASTQ format (files compressed with gzip are allowed).
> --mp2 <path>
> File with reverse mate-pair reads in FASTQ format (files compressed with gzip are allowed).
> --mp12 <path>
> File with interlaced forward and reverse mate-pair reads in FASTQ format (files compressed with gzip are allowed).
> --single <path>
> File with unpaired reads in FASTQ format (files compressed with gzip are allowed).
> 
 is it possible to specify 10X reads as Quast-LG input?

**Comment by alexeigurevich** [comment]
Hi, I've just improved the documentation regarding this.

> how should multiple input libraries be specified?

Specifying multiple libs/files is pretty simple -- just prepend each file you want to specify with the corresponding option (each option can be specified an unlimited number of times). For example:
`--pe1 lib1/R1.fq --pe2 lib1/R2.fq --pe1 lib2/R1.fq.gz --pe2 lib2/R2.fq.gz`.

> is it possible to specify 10X reads as Quast-LG input?

No. Currently, the supported read types are Illumina unpaired, paired-end and mate-pair reads, PacBio SMRT, and Oxford Nanopore long reads. We are thinking about supporting optical maps and may be 10X reads, too. But such plans are for far future.

**Comment by silfalqueto** [comment]
Hi. I'm assembling a prokaryote genome, and I'm having the same problem. 
I have four PE libraries and I get the same message: ERROR! Use the SAME number of files with forward and reverse reads for paired-end libraries (-1 <filepath> -2 <filepath>)

here's my code:
quast.py -r ./Bvel_NZ_CP011937.1.fa --gene-finding \
--pe1 L1R1417p70.fastq \
--pe2 L1R2417p70.fastq \
--pe1 L2R1417p70.fastq \ 
--pe2 L2R2417p70.fastq \
-m 0 -t 1 \
-o quast_eval \
    ./454Scaffolds.fna \
    ./contigs.fa \
    ./Scaffolds.fasta \
    ./megamerge_asm.fa

Can you help me?
