### ISSUE TITLE
[Errno 36] File name too long in k-mer-stats

### ISSUE THREAD

**Issue by hilynano** [ablab/quast#67]
k-mers seems to create a super long name in kmer analyses.

kmers_2Cen_mapped_Scaffold_10_D1684_type_golden_path_region__loc_2Cen_mapped_Scaffold_10_D1684_1..19956__ID_2Cen_mapped_Scaffold_10_D1684__dbxref_GB_CP007071_GB_CP007071_REFSEQ_NW_007931073__MD5_b71b59981d0bc7d367792f99638e8ff5__length_19956__release_r6.12__species_Dmel_.fasta

My original ref fasta name is >2Cen_mapped_Scaffold_10_D1684 type=golden_path_region; loc=2Cen_mapped_Scaffold_10_D1684:1..19956; ID=2Cen_mapped_Scaffold_10_D1684; dbxref=GB:CP007071,GB:CP007071,REFSEQ:NW_007931073; MD5=b71b59981d0bc7d367792f99638e8ff5; length=19956; release=r6.12; species=Dmel;

I can easily modify my ref fasta to make it work, but I think that it's better for you to fix it since most reference from NCBI or other databases will have these long names.

**Comment by alexeigurevich** [comment]
Thanks for your suggestion! We modified our FASTA reading procedure, so now we ignore everything after the first whitespace, e.g. in your case
`>2Cen_mapped_Scaffold_10_D1684 type=golden_path_region; loc=2Cen_mapped_Scaffold_10_D1684:1..19956; ID=2Cen_mapped_Scaffold_10_D1684; dbxref=GB:CP007071,GB:CP007071,REFSEQ:NW_007931073; MD5=b71b59981d0bc7d367792f99638e8ff5; length=19956; release=r6.12; species=Dmel;`
will be stored internally as `2Cen_mapped_Scaffold_10_D1684` and further used in intermediate filenames like `kmers_....fasta`. Thus, the filenames will become much shorter in cases like yours.

See also somehow related issue: https://github.com/ablab/quast/issues/69
