### ISSUE TITLE
specifying inputs

### ISSUE THREAD

**Issue by mossishahi** [ablab/quast#68]
Hi!
I would like to use Quast 5 in order to do some analysis by aligning 12 libraries of paired-end and mate pair reads. in a command like this:
``` ./quast.py -r ~/e/Planaria_10X/Fastq/For_10x_Denovo_Data/PG2103_03BE5/Fastq/longranger-indexed/tigmint/DjScaff_fnl20141213.fa -o ~/e/Planaria_10X/quast/ --large --pe1 /s/chopin/a/grad/asharifi/e/Planaria/Genome_Rawseq/Illumina/Dj_matepair/afterQC-fq/Sample_Ip1683_500b_1.fastq --pe2 /s/chopin/a/grad/asharifi/e/Planaria/Genome_Rawseq/Illumina/Dj_matepair/afterQC-fq/Sample_Ip1683_500b_2.fastq --pe1 /s/chopin/a/grad/asharifi/e/Planaria/Genome_Rawseq/Illumina/GAII/all-Lanes/afterQC-fq/total-libs/Lib1.fq --pe2 /s/chopin/a/grad/asharifi/e/Planaria/Genome_Rawseq/Illumina/GAII/all-Lanes/afterQC-fq/total-libs/Lib2.fq --pe1 /s/chopin/a/grad/asharifi/e/Planaria/Genome_Rawseq/Illumina/Hisseq2000-3000500bp-110331/afterQc-fq/total-libs/Lib1.fq --pe2 /s/chopin/a/grad/asharifi/e/Planaria/Genome_Rawseq/Illumina/Hisseq2000-3000500bp-110331/afterQc-fq/total-libs/Lib2.fq --mp1 /s/chopin/a/grad/asharifi/e/Planaria/Genome_Rawseq/Illumina/Dj_matepair/afterQC-fq/Sample_Ip1683-1694_20kb_1.fastq --mp2 /s/chopin/a/grad/asharifi/e/Planaria/Genome_Rawseq/Illumina/Dj_matepair/afterQC-fq/Sample_Ip1683-1694_20kb_2.fastq --mp1 /s/chopin/a/grad/asharifi/e/Planaria/Genome_Rawseq/Illumina/Dj_matepair/afterQC-fq/Sample_Ip1683-1694_8kb_1.fastq --mp2 /s/chopin/a/grad/asharifi/e/Planaria/Genome_Rawseq/Illumina/Dj_matepair/afterQC-fq/Sample_Ip1683-1694_8kb_2.fastq --mp1 /s/chopin/a/grad/asharifi/e/Planaria/Genome_Rawseq/Illumina/Dj_matepair/afterQC-fq/Sample_Ip1683_3kb_1.fastq --mp2 /s/chopin/a/grad/asharifi/e/Planaria/Genome_Rawseq/Illumina/Dj_matepair/afterQC-fq/Sample_Ip1683_3kb_2.fastq```
that this error occured:

`ERROR! You should specify at least one file with contigs!
`
I am considering that it means the reads by contig files.

**Comment by alexeigurevich** [comment]
Hi!
Quast is first of all genome assembly analysis tool, so we _require_ at least one assembly to start the processing (i.e. a file with contigs/scaffolds as stated in the error message). Note that you do not need to specify any options before assembly file paths, so any file not prefixed by an option is considered as an assembly file.

If you don't have any assembly but still want to perform read alignments (against the reference genome) and get some stats, you can "cheat" and specify the reference twice -- as a reference (`-r` option) and as an assembly (without option). So, the beginning of your running command will look like:
`./quast.py -r ~/e/Planaria_10X/Fastq/For_10x_Denovo_Data/PG2103_03BE5/Fastq/longranger-indexed/tigmint/DjScaff_fnl20141213.fa ~/e/Planaria_10X/Fastq/For_10x_Denovo_Data/PG2103_03BE5/Fastq/longranger-indexed/tigmint/DjScaff_fnl20141213.fa -o ~/e/Planaria_10X/quast/`

However, Quast is probably not the best tool for the read analysis ***only*** and it will perform some assembly-related additional steps like aligning the reference against itself.

**Comment by alexeigurevich** [comment]
Hi, this is our bug in `reads_analyzer.py` module -- I've just fixed it in the repo (see [
782fecd](https://github.com/ablab/quast/commit/782fecd5646012d3b4a15c491a0b9bf7056bc656)). You could simply open `/s/damavand/e/asharifi/Applications/quast-5.0.0/quast_libs/reads_analyzer.py` in any text editor, and substitute
`sort_bam(bam_fpath, bam_sorted_fpath, log_path, err_fpath, logger)`
with
`sort_bam(bam_fpath, bam_sorted_fpath, err_fpath, logger)`
on line 803.
Thanks for reporting!

**Comment by mossishahi** [comment]
@alexeigurevich thanks. Is there any way to follow the instructions has been done or should start from scratch?
One other question I repeat it: In our case which there is no reference, Does Quast report any possible misassemblies like those which caused by the reads more than 1000 mutual bp?
Thanks

**Comment by mossishahi** [comment]
@alexeigurevich reminder!

**Comment by alexeigurevich** [comment]
Hi @mossishahi,
I am sorry -- wrote an answer to you 6 days ago but seems to press "Preview' instead of "Comment". 
Here is the original text:

"Thanks for the reminder, the issue was closed, so I missed the original question. Feel free to reopen an issue if I am not answering for a while.
> Is there any way to follow the instructions has been done or should start from scratch?

You can simply run Quast with the same output dir specified and it will try to reuse already generated files and skip the corresponding steps of the pipeline.

>One other question I repeat it: In our case which there is no reference, Does Quast report any possible misassemblies like those which caused by the reads more than 1000 mutual bp?

Unfortunately, Quast reports only reference-based misassemblies, we are not looking for misassemblies confirmed by reads. For read-based misassemblies statistics you may take a look at [REAPR](https://www.sanger.ac.uk/science/tools/reapr). Some time ago, we tested several reference-free evaluation tools and REAPR showed the best results, albeit still not very good in some experiments (too many false positive misassemblies). We are thinking about adding similar functionality to Quast but it is a far future plan.
