### ISSUE TITLE
Error pre-processing reads

### ISSUE THREAD

**Issue by neumannguib** [ablab/quast#72]
**Hello,
I\`ve been in trouble with some input reads. I\`ve downloaded them from NCBI and also from ENA, trying to remove techincal reads and even some artificial sequence names but the problem persists. The format follows the standard NCBI fastq. Should I try some specific pre-processing step before submitting them to quast ? Which format should I try ?
The problem happens to many species and reads, but not to all.**

```
Contigs:
  Pre-processing...

    ERROR! Skipping /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467887_1.fastq.gz because it contains non-ACGTN characters.

    ERROR! Skipping /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467887_2.fastq.gz because it contains non-ACGTN characters.

    ERROR! Skipping /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467888_subreads.fastq.gz because >sequence_name field is empty.

    ERROR! Skipping /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467891_2.fastq.gz because >sequence_name field is empty.

    ERROR! Skipping /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467889_2.fastq.gz because >sequence_name field is empty.

    ERROR! Skipping /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467892_subreads.fastq.gz because >sequence_name field is empty.

    ERROR! Skipping /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467886_subreads.fastq.gz because >sequence_name field is empty.

    ERROR! Skipping /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467890_subreads.fastq.gz because >sequence_name field is empty.

    ERROR! Skipping /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467889_1.fastq.gz because >sequence_name field is empty.

    ERROR! Skipping /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467891_1.fastq.gz because >sequence_name field is empty.

    ERROR! Skipping /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467893_1.fastq.gz because >sequence_name field is empty.

    ERROR! Skipping /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467893_2.fastq.gz because >sequence_name field is empty.
```

Thank you, 
Guilherme Neumann

**Comment by alexeigurevich** [comment]
Hi Guilherme,
It looks like Quast tries to interpret your reads as assemblies (should be always in FASTA, maybe compressed) and that is why Quast fails to parse them -- the third line of a FASTQ file doesn't have ">sequence_name" and the fourth line include non-ACGT characters. 

For providing reads you should prepend each filepath with an appropriate option depending on read type (e.g. `-1`, `-2` for left and right paired-end reads, `--mp12` for interlaced mate-pairs, `-s` for unpaired reads, etc). All filepaths without an option before are considered as assemblies by default.

An example of correct command:
`python quast.py -r reference.fasta assembly.fasta -o output_dir -1  /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467893_1.fastq.gz -2 /mnt/data-assemblies/bacteria/Mtuberculosis/SRR6467893_2.fastq.gz`

**Comment by alexeigurevich** [comment]
Yes, exactly! You need to prepend each read file with the appropriate option.
