### ISSUE TITLE
"Can't draw plots: python-matplotlib is missing or corrupted" only in compute nodes on a openHPC cluster

### ISSUE THREAD

**Issue by ghbio** [ablab/quast#75]
Hello!

I have installed version 5.0.1 in the master node of an openHPC cluster using virtualenv under python 2.7.15 and `./setup.py install_full`. After installation I had to install matplotlib in the virtualenv with pip.

Running quast in the master node runs with no problem, but when running it in any of the compute nodes fail to create the plots with this warning message:

```
WARNING: Can't draw plots: python-matplotlib is missing or corrupted.
```

In any of the compute nodes, after activating the environment, I can launch a python console and check whether matplotlib is there (and it is) with

```
from matplotlib import *
```

I don't know if the problem is in the cluster configuration end, so I'd appreciate any lead that you may have regarding this issue.

Thanks!
Pablo

**Comment by alexeigurevich** [comment]
Hello Pablo,

I suppose that when you run Quast on the compute nodes your virtualenv is not activated. Actually, our warning in 99% cases means `ImportError` on executing `import matplotlib`. See the [corresponding code](https://github.com/ablab/quast/blob/master/quast_libs/plotter.py#L72).

I think the best solution for you is to install Quast via pip, too (`pip install quast` -- version 5.0.1 is already available there) and remove your manually installed Quast. In this case, if you run Quast from pip it should catch your pip-installed matplotlib as well. Alternatively, try to ensure that the environment with matplotlib is really activated when you run the current Quast (and it uses the same Python executable as in your environment is).

**Comment by isgilman** [comment]
I'm still experiencing the same issue after installing everything with conda.

`which python`: /ysm-gpfs/home/isg4/anaconda2/bin/python
`which quast`:  /ysm-gpfs/home/isg4/anaconda2/bin/quast
`matplotlib.__file__` : /ysm-gpfs/home/isg4/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.pyc

And checking `conda list` I see quast along with all it's dependencies. 

I may be missing something very straightforward here. Any suggestions?

**Comment by tenlives** [comment]
> I'm still experiencing the same issue after installing everything with conda.
> 
> `which python`: /ysm-gpfs/home/isg4/anaconda2/bin/python
> `which quast`: /ysm-gpfs/home/isg4/anaconda2/bin/quast
> `matplotlib.__file__` : /ysm-gpfs/home/isg4/anaconda2/lib/python2.7/site-packages/matplotlib/**init**.pyc
> 
> And checking `conda list` I see quast along with all it's dependencies.
> 
> I may be missing something very straightforward here. Any suggestions?

i check the matplotlib whether can work well,so i run python3 and import matplotlib.pyplot .it raises an error that ImportError: libpng16.so.16: cannot open shared object file: No such file or directory. so i re-configurate the libpng ,and run the command sudo ldconfig. Then it works

**Comment by tenlives** [comment]
i check the matplotlib whether can work well,so i run python3 and import matplotlib.pyplot .it raises an error that ImportError: libpng16.so.16: cannot open shared object file: No such file or directory. so i re-configurate the libpng ,and run the command sudo ldconfig. Then it works

**Comment by herokoking** [comment]
**solution**:
    sudo yum install -y python-matplotlib
