### ISSUE TITLE
output file naming

### ISSUE THREAD

**Issue by nick-youngblut** [ablab/quast#76]
This is a small, but annoying thing about quast (at least metaquast): many of the output files in the ./summary/ directory are named with non-standard characters, and so they are in quotes. For instance:

```
Avg_contig_read_support.tsv
'#_contigs.tsv'
Duplication_ratio.tsv
'#_genes.tsv'
'Genome_fraction_(%).tsv'
'#_indels_per_100_kbp.tsv'
Largest_alignment.tsv
Largest_contig.tsv
LGA50.tsv
Misassembled_contigs_length.tsv
'#_misassemblies.tsv'
'#_mismatches_per_100_kbp.tsv'
NGA50.tsv
"#_N's_per_100_kbp.tsv"
'#_operons.tsv'
'#_predicted_genes_(unique).tsv'
Total_aligned_length.tsv
'Total_length_(>=_10000_bp).tsv'
'Total_length_(>=_1000_bp).tsv'
'Total_length_(>=_50000_bp).tsv'
Total_length.tsv
```

The non-standard characters and quotes in the file names makes opening these files in R, python, etc a real pain. Why can't "#" just be "Number"? Why not "gte" instead of ">="?

**Comment by alexeigurevich** [comment]
Hi!
Actually, this was fixed in 5.0.0 release, see #8 in [CHANGES](http://cab.spbu.ru/files/quast/latest-docs/CHANGES.txt). And yes, the problem was related to metaQuast summary reports only.
