### ISSUE TITLE
NG75 column omitted in transposed_report.tsv

### ISSUE THREAD

**Issue by sjackman** [ablab/quast#82]
When less than 75% of the genome is assembled, the NG75 column is omitted. That makes it difficult to combine reports from different runs of QUAST, since columns after that will be in different positions. Could a that column be present but instead filled with `NA`?

**Comment by almiheenko** [comment]
Hi Shaun!
Thanks for reporting this issue. I added a fix, so now all these metrics should always be present in a report, and the number of columns should be the same in all reports.

**Comment by sjackman** [comment]
Thanks for the quick fix!
