### ISSUE TITLE
Error installing Quast! Compilation of contig aligner software was unsuccessful!

### ISSUE THREAD

**Issue by shimingt** [ablab/quast#87]
Hello there,

I have a problem installing Quast. 
[install_log.stdout.txt](https://github.com/ablab/quast/files/2739329/install_log.stdout.txt)

I see I have a problem with the compilation of the contig aligner software. Can anyone help me out please?

Thank you!

**Comment by alexeigurevich** [comment]
Hello!
The actual issue aborting the compilation is in `/home/tanshiming/tools/quast-5.0.2/quast_libs/minimap2/make.err` (or in `make.log` nearby). I suppose that you don't have zlib-dev files which are among the Quast v.5.0 prerequisites and required for `minimap2` compilation (our contig aligner software). You can install it on Ubuntu using 
`sudo apt-get install zlib1g-dev`

After that, please remove `/home/tanshiming/tools/quast-5.0.2/quast_libs/minimap2/make.failed` (to enable recompilation of `minimap2`) and rerun the installation script (or simply run `quast.py --test --fast`). If it doesn't help, please reopen the issue and attach `make.err` and `make.log` files mentioned above.

Also, note that you can install Quast v.5.0.2 via pip (`pip install quast`) or bioconda (`conda install -c bioconda quast`) -- they should handle all dependencies for you.

**Comment by shimingt** [comment]
Dear @alexeigurevich,

Thanks for your reply! Let me try it out with bioconda.

**Comment by SoSongzhi** [comment]
Hello there,

I have a problem using Quast.

"ERROR! Compilation of contig aligner software was unsuccessful! QUAST functionality will be limited.
Failed aligning the contigs for all the assemblies. Only basic stats are going to be evaluated."

Can anyone help me out please?

Thank you.
