### ISSUE TITLE
gene prediction with metaquast

### ISSUE THREAD

**Issue by lalalagartija** [ablab/quast#89]
Is quast the right tool to use to predict genes if I don't know if it is eukaryotic or prokaryotic ? How does gene prediction works in quast and is it better than directly running Metagenemark for example ?

Thank you very much in advance,

**Comment by alexeigurevich** [comment]
Quast incorporates multiple third-party gene prediction tools but we don't perform any extra prediction procedures ourselves. So, you can run MetaGeneMark (or GlimmerHMM, or GeneMarkS, or GeneMark-ES) directly and get absolutely the same results (we mostly use default settings everywhere). The benefit of using these tools within Quast is nice output text and visual/interactive reports, so it would be easy to compare the number of predicted genes and their lengths, positions in assemblies, etc. 

If you don't know whether an organism is eukaryotic or prokaryotic you may try to run Quast in both modes (default is prokaryotic, use `--eukaryote` for enabling eukaryotic analysis) and find out which results looks more trustful/consistent. E.g. you may check the percent of identified eukaryotic/prokaryotic conservative genes (computed with BUSCO if you use `--conserved-genes-finding` or `-b` option).
