### ISSUE TITLE
Error with features flag "'i' format requires -2147483648 <= number <= 2147483647"

### ISSUE THREAD

**Issue by Ritu-Kundu** [ablab/quast#92]
Hi,

I am running into an error (attached
[quast_error.txt](https://github.com/ablab/quast/files/2933532/quast_error.txt)) while using --features with [this](ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gff.gz) feature file and [this](ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz) human reference.

I have tried conda installation of quast (separate environment, quast version: 5.0.2, python version 3.6.7) as well as installation from source (quast version: 5.0.2, python version: tried both with 3.6.3 and 3.6.7) but each trial ended up with the same error.  What could I change to get rid of the error?

**Comment by almiheenko** [comment]
Hi,

This is can be an issue with joblib library, that provides multiprocessing support. Could you try to re-run QUAST on the same folder with an option "-t 1", to run everything using one thread? 

Also, could you please upload your feature file and reference file for debugging? You can privately send them to quast.support@cab.spbu.ru. Thanks!

**Comment by Ritu-Kundu** [comment]
Hi,

Thanks. Running on one thread worked for me. The feature file and the reference can be downloaded from the following links, respectively:
[Features](ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gff.gz):
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gff.gz
[Ref](ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gff.gz):
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

I am using no-alt-analysis version of GRCh38 as reference which doesn't have corresponding features file. Therefore, I had to use corresponding full-analysis features file.
