### ISSUE TITLE
Error when generating upper bound assembly

### ISSUE THREAD

**Issue by haghshenas** [ablab/quast#93]
Hello,

First of all thanks for this nice piece of software.
I'm using QUAST 5.0.2 and gave the upper bound assembly a try. Here is my command:
```
/home/ehaghshe/softwares/quast-5.0.2/quast.py -o quast -r ref.fa --upper-bound-assembly --no-sv --no-read-stats --pacbio lr.fasta -l asm asm.contigs.fasta
```
and here is the error I get:
```
2019-03-09 00:17:20
Generating Upper Bound Assembly...
  Pre-processing reads...
  Running BWA for reference...
  Done.
  Sorting SAM-file for reference...
  Calculating reads coverage...
  Running repeat masking tool...
  Pre-processing reads...
  Running BWA for reference...
  Done.
  Sorting SAM-file for reference...

'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/home/ehaghshe/softwares/quast-5.0.2/quast.py", line 307, in <module>
    return_code = main(sys.argv[1:])
  File "/home/ehaghshe/softwares/quast-5.0.2/quast.py", line 95, in main
    os.path.join(output_dirpath, qconfig.optimal_assembly_basename))
  File "/home/ehaghshe/softwares/quast-5.0.2/quast_libs/optimal_assembly.py", line 490, in do
    joiners = get_joiners(qutils.name_from_fpath(ref_fpath), sam_fpath, bam_fpath, tmp_dir, log_fpath, join_reads)
  File "/home/ehaghshe/softwares/quast-5.0.2/quast_libs/optimal_assembly.py", line 106, in get_joiners
    bed_fpath = bam_to_bed(output_dirpath, using_reads, bam_sorted_fpath, err_fpath, logger, bedpe=using_reads == 'mp')
  File "/home/ehaghshe/softwares/quast-5.0.2/quast_libs/ra_utils/misc.py", line 351, in bam_to_bed
    stdout=open(raw_bed_fpath, 'w'), stderr=open(err_path, 'a'), logger=logger)
  File "/home/ehaghshe/softwares/quast-5.0.2/quast_libs/qutils.py", line 623, in call_subprocess
    if arg.startswith(os.getcwd()):
AttributeError: 'NoneType' object has no attribute 'startswith'
ERROR! exception caught!
```
Any ideas how to fix this? Thanks a lot.

**Comment by almiheenko** [comment]
Hi Ehsan,

It seems that there is an issue with bedtools bamToBed utility. Could you please try to substitute the following file with the attached file: /home/ehaghshe/softwares/quast-5.0.2/quast_libs/ra_utils/misc.py. If the issue persists, please let us know and upload the quast/quast.log file for debugging.

Best regards,
Alla
[misc.py.zip](https://github.com/ablab/quast/files/2957235/misc.py.zip)

**Comment by haghshenas** [comment]
Thanks for the response. It seems the new `misc.py` fixed the issue with generating the upper bound assembly, but there is still some errors. I have attached the log file.

To clarify, when I use the generated upper bound assembly as an additional assembly in a new clean run without options `--upper-bound-assembly --no-sv --no-read-stats --pacbio lr.fasta` everything works.

[quast.log](https://github.com/ablab/quast/files/2963279/quast.log)

**Comment by almiheenko** [comment]
Hi Ehsan,

Could you try to substitute also the following file with the attached file [reads_analyzer.py.zip](https://github.com/ablab/quast/files/2968250/reads_analyzer.py.zip): /home/ehaghshe/softwares/quast-5.0.2/quast_libs/reads_analyzer.py. 

Sorry for the inconvenience!

**Comment by haghshenas** [comment]
Hi again,

Yes! It is working now.
Thanks
